using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace DLL.Migrations
{
    public partial class updateloaihoadontotruongdl : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("Update TruongDuLieuHoaDons " +
                                "Set LoaiHoaDon = 0 Where STT >=1 and STT<=36 and IsChiTiet = 0");
            migrationBuilder.Sql("Update TruongDuLieuHoaDons " +
                    "Set LoaiHoaDon = 1 Where STT >=1 and STT<=36 and (IsMoRong = 1 and IsChiTiet = 1) or IsChiTiet = 1");
            migrationBuilder.InsertData(
                table: "TruongDuLieuHoaDons",
                columns: new string[] {
                       "Id"
                    , "STT"
                    , "MaTruong"
                    , "TenTruong"
                    , "TenTruongData"
                    , "GhiChu"
                    , "IsChiTiet"
                    , "IsMoRong"
                    , "Status"
                    , "Default"
                    , "Size"
                    , "Align"
                    , "DefaultSTT"
                    , "DinhDangSo"
                    , "LoaiHoaDon"
                },
                values: new object[,] {
                    {
                        Guid.NewGuid().ToString(),
                        1,
                        "HHDV 1",
                        "STT",
                        "STT",
                        "",
                        true,
                        false,
                        true,
                        true,
                        50,
                        "center",
                        1,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        2,
                        "HHDV 2",
                        "Mã hàng",
                        "MaHang",
                        "",
                        true,
                        false,
                        true,
                        true,
                        120,
                        "left",
                        2,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        3,
                        "HHDV 3",
                        "Tên hàng",
                        "TenHang",
                        "",
                        true,
                        false,
                        true,
                        true,
                        150,
                        "left",
                        3,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        4,
                        "HHDV 4",
                        "Hàng khuyến mại",
                        "HangKhuyenMai",
                        "",
                        true,
                        false,
                        true,
                        true,
                        130,
                        "center",
                        4,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        5,
                        "HHDV 5",
                        "Mã quy cách",
                        "MaQuyCach",
                        "",
                        true,
                        false,
                        false,
                        false,
                        130,
                        "left",
                        5,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        6,
                        "HHDV 6",
                        "ĐVT",
                        "DonViTinh",
                        "",
                        true,
                        false,
                        true,
                        true,
                        100,
                        "left",
                        6,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        7,
                        "HHDV 7",
                        "Số lượng",
                        "SoLuong",
                        "",
                        true,
                        false,
                        true,
                        true,
                        200,
                        "right",
                        7,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        8,
                        "HHDV 8",
                        "Đơn giá sau thuế",
                        "DonGiaSauThue",
                        "",
                        true,
                        false,
                        false,
                        false,
                        150,
                        "right",
                        8,
                        true,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        9,
                        "HHDV 9",
                        "Đơn giá",
                        "DonGia",
                        "",
                        true,
                        false,
                        true,
                        true,
                        150,
                        "left",
                        9,
                        true,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        10,
                        "HHDV 10",
                        "Thành tiền sau thuế",
                        "ThanhTienSauThue",
                        "",
                        true,
                        false,
                        false,
                        false,
                        200,
                        "right",
                        10,
                        true,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        11,
                        "HHDV 11",
                        "Thành tiền",
                        "ThanhTien",
                        "",
                        true,
                        false,
                        true,
                        true,
                        150,
                        "right",
                        11,
                        true,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        12,
                        "HHDV 12",
                        "Thành tiền quy đổi",
                        "ThanhTienQuyDoi",
                        "",
                        true,
                        false,
                        false,
                        false,
                        150,
                        "left",
                        12,
                        true,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        13,
                        "HHDV 13",
                        "Tỷ lệ chiết khấu",
                        "TyLeChietKhau",
                        "",
                        true,
                        false,
                        true,
                        true,
                        150,
                        "right",
                        13,
                        true,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        14,
                        "HHDV 14",
                        "Tiền chiết khấu",
                        "TienChietKhau",
                        "",
                        true,
                        false,
                        true,
                        true,
                        150,
                        "right",
                        14,
                        true,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        15,
                        "HHDV 15",
                        "Tiền chiết khấu quy đổi",
                        "TienChietKhauQuyDoi",
                        "",
                        true,
                        false,
                        false,
                        false,
                        150,
                        "right",
                        15,
                        true,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        16,
                        "HHDV 16",
                        "% Thuế GTGT",
                        "ThueGTGT",
                        "",
                        true,
                        false,
                        true,
                        true,
                        150,
                        "right",
                        16,
                        true,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        17,
                        "HHDV 17",
                        "Tiền thuế GTGT",
                        "TienThueGTGT",
                        "",
                        true,
                        false,
                        true,
                        true,
                        150,
                        "left",
                        17,
                        true,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        18,
                        "HHDV 18",
                        "Tiền thuế GTGT quy đổi",
                        "TienThueGTGTQuyDoi",
                        "",
                        true,
                        false,
                        false,
                        false,
                        150,
                        "right",
                        18,
                        true,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        19,
                        "HHDV 19",
                        "Số lô",
                        "SoLo",
                        "",
                        true,
                        false,
                        false,
                        false,
                        150,
                        "left",
                        19,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        20,
                        "HHDV 20",
                        "Hạn sử dụng",
                        "HanSuDung",
                        "",
                        true,
                        false,
                        false,
                        false,
                        180,
                        "center",
                        20,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        21,
                        "HHDV 21",
                        "Số khung",
                        "SoKhung",
                        "",
                        true,
                        false,
                        false,
                        false,
                        150,
                        "left",
                        21,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        22,
                        "HHDV 22",
                        "Số máy",
                        "SoMay",
                        "",
                        true,
                        false,
                        false,
                        false,
                        150,
                        "left",
                        22,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        23,
                        "HHDV 23",
                        "Xuất bản phí",
                        "XuatBanPhi",
                        "",
                        true,
                        false,
                        false,
                        false,
                        200,
                        "right",
                        23,
                        true,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        24,
                        "HHDV 24",
                        "Ghi chú",
                        "GhiChu",
                        "",
                        true,
                        false,
                        false,
                        false,
                        200,
                        "left",
                        24,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        25,
                        "HHDV 25",
                        "Mã nhân viên",
                        "MaNhanVien",
                        "",
                        true,
                        false,
                        false,
                        false,
                        150,
                        "left",
                        25,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        26,
                        "HHDV 26",
                        "Tên nhân viên",
                        "TenNhanVien",
                        "",
                        true,
                        false,
                        false,
                        false,
                        150,
                        "left",
                        26,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        27,
                        "HHDV 27",
                        "Trường mở rộng chi tiết số 1",
                        "TruongMoRongChiTiet1",
                        "",
                        true,
                        true,
                        false,
                        false,
                        150,
                        "left",
                        27,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        28,
                        "HHDV 28",
                        "Trường mở rộng chi tiết số 2",
                        "TruongMoRongChiTiet2",
                        "",
                        true,
                        true,
                        false,
                        false,
                        150,
                        "left",
                        28,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        29,
                        "HHDV 29",
                        "Trường mở rộng chi tiết số 3",
                        "TruongMoRongChiTiet3",
                        "",
                        true,
                        true,
                        false,
                        false,
                        150,
                        "left",
                        29,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        30,
                        "HHDV 30",
                        "Trường mở rộng chi tiết số 4",
                        "TruongMoRongChiTiet4",
                        "",
                        true,
                        true,
                        false,
                        false,
                        150,
                        "left",
                        30,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        31,
                        "HHDV 31",
                        "Trường mở rộng chi tiết số 5",
                        "TruongMoRongChiTiet5",
                        "",
                        true,
                        true,
                        false,
                        false,
                        150,
                        "left",
                        31,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        32,
                        "HHDV 32",
                        "Trường mở rộng chi tiết số 6",
                        "TruongMoRongChiTiet6",
                        "",
                        true,
                        true,
                        false,
                        false,
                        150,
                        "left",
                        32,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        33,
                        "HHDV 33",
                        "Trường mở rộng chi tiết số 7",
                        "TruongMoRongChiTiet7",
                        "",
                        true,
                        true,
                        false,
                        false,
                        150,
                        "left",
                        33,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        34,
                        "HHDV 34",
                        "Trường mở rộng chi tiết số 8",
                        "TruongMoRongChiTiet8",
                        "",
                        true,
                        true,
                        false,
                        false,
                        150,
                        "left",
                        34,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        35,
                        "HHDV 35",
                        "Trường mở rộng chi tiết số 9",
                        "TruongMoRongChiTiet9",
                        "",
                        true,
                        true,
                        false,
                        false,
                        150,
                        "left",
                        35,
                        false,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        36,
                        "HHDV 36",
                        "Trường mở rộng chi tiết số 10",
                        "TruongMoRongChiTiet10",
                        "",
                        true,
                        true,
                        false,
                        false,
                        150,
                        "left",
                        36,
                        false,
                        2
                    },
                });

            migrationBuilder.Sql("Update ThietLapTruongDuLieuMoRongs " +
                    "Set LoaiHoaDon = 1");
            migrationBuilder.InsertData(
                table: "ThietLapTruongDuLieuMoRongs",
                columns: new string[] { "Id", "TenTruong", "TenTruongHienThi", "GhiChu", "HienThi", "LoaiHoaDon" },
                values: new object[,]
                {
                    {
                        Guid.NewGuid().ToString(),
                        "Trường thông tin bổ sung 1",
                        "Trường thông tin bổ sung 1",
                        string.Empty,
                        true,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        "Trường thông tin bổ sung 2",
                        "Trường thông tin bổ sung 2",
                        string.Empty,
                        true,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        "Trường thông tin bổ sung 3",
                        "Trường thông tin bổ sung 3",
                        string.Empty,
                        true,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        "Trường thông tin bổ sung 4",
                        "Trường thông tin bổ sung 4",
                        string.Empty,
                        true,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        "Trường thông tin bổ sung 5",
                        "Trường thông tin bổ sung 5",
                        string.Empty,
                        true,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        "Trường thông tin bổ sung 6",
                        "Trường thông tin bổ sung 6",
                        string.Empty,
                        true,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        "Trường thông tin bổ sung 7",
                        "Trường thông tin bổ sung 7",
                        string.Empty,
                        true,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        "Trường thông tin bổ sung 8",
                        "Trường thông tin bổ sung 8",
                        string.Empty,
                        true,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        "Trường thông tin bổ sung 9",
                        "Trường thông tin bổ sung 9",
                        string.Empty,
                        true,
                        2
                    },
                    {
                        Guid.NewGuid().ToString(),
                        "Trường thông tin bổ sung 10",
                        "Trường thông tin bổ sung 10",
                        string.Empty,
                        true,
                        2
                    },

                });

            migrationBuilder.Sql("Update TruongDuLieuHoaDons set TenTruongHienThi = TenTruong");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
