using Microsoft.EntityFrameworkCore.Migrations;

namespace DLL.Migrations
{
    public partial class insertdatatruongthietlapdulieu : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DELETE FROM ThietLapTruongDuLieus
                GO
                
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'01e15543-1936-4176-a4c3-d6105562e210', N'', N'MaTraCuu', N'Mã tra cứu', N'Mã tra cứu', 0, 0, 1, N'', 130, 20, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'024aa7fc-ebf5-46b1-ab33-d180d3ef23db', N'HHDV 33', N'TruongMoRongChiTiet7', N'Trường mở rộng chi tiết số 7', N'Trường mở rộng chi tiết số 7', 1, 2, 1, N'', 170, 33, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'05f6bc06-2f86-4c1a-97ba-3317363647ee', N'HHDV 15', N'TienChietKhauQuyDoi', N'Tiền chiết khấu quy đổi', N'Tiền chiết khấu quy đổi', 1, 2, 2, N'', 140, 15, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'06644d25-5b1d-4ab1-9043-ccecffbcabf3', N'', N'DiaChi', N'Địa chỉ', N'Địa chỉ', 0, 0, 1, N'', 200, 8, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'0b629dcd-6181-4174-8b05-53ecdda60ce9', N'HHDV 19', N'SoLo', N'Số lô', N'Số lô', 2, 2, 1, N'', 130, 19, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'0bce6ce8-14e3-4c96-9b03-cf5b689df842', N'', N'TruongThongTinBoSung3', N'Trường thông tin bổ sung 3', N'Trường thông tin bổ sung 3', 0, 0, 1, N'', 180, 33, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'0c0b6955-9698-4bcc-b675-ed5c9e197112', N'', N'TruongThongTinBoSung9', N'Trường thông tin bổ sung 9', N'Trường thông tin bổ sung 9', 1, 1, 1, N'', NULL, 9, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'0dba70b4-e1ec-4cf7-a5e5-7c34735bc848', N'HHDV 14', N'TienChietKhau', N'Tiền chiết khấu', N'Tiền chiết khấu', 2, 2, 2, N'', 130, 14, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'0f28d539-dee1-423a-90df-38bc2a88d7f5', N'HHDV 22', N'SoMay', N'Số máy', N'Số máy', 1, 2, 1, N'', 130, 22, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'110b8634-4c5a-495e-8a79-f7cc69119d92', N'HHDV 1', N'STT', N'STT', N'STT', 1, 2, 3, N'', 50, 1, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'13f363a0-fbe1-4345-bded-582b0a0e4da8', N'', N'TenKhachHang', N'Tên khách hàng', N'Tên khách hàng', 0, 0, 1, N'', 180, 7, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'18ff1865-0d03-409f-ac74-59d1c238241f', N'', N'TruongThongTinBoSung10', N'Trường thông tin bổ sung 10', N'Trường thông tin bổ sung 10', 2, 1, 1, N'', NULL, 10, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'1d803534-c066-4020-9630-ee307fcaddea', N'', N'TruongThongTinBoSung9', N'Trường thông tin bổ sung 9', N'Trường thông tin bổ sung 9', 0, 0, 1, N'', 180, 39, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'1fdc4d46-3c4c-499c-b8ff-90703c6bdd9d', N'HHDV 33', N'TruongMoRongChiTiet7', N'Trường mở rộng chi tiết số 7', N'Trường mở rộng chi tiết số 7', 2, 2, 1, N'', 170, 33, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'2045d077-1190-45ad-b9d3-2a415ce2cfd3', N'HHDV 8', N'DonGiaSauThue', N'Đơn giá sau thuế', N'Đơn giá sau thuế', 1, 2, 2, N'', 130, 8, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'205c19a0-4e05-4ffb-a3d6-47acd03c4c07', N'', N'TruongThongTinBoSung1', N'Trường thông tin bổ sung 1', N'Trường thông tin bổ sung 1', 2, 1, 1, N'', NULL, 1, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'212a1c21-2f3a-4759-9463-43a273d02dbb', N'', N'TruongThongTinBoSung8', N'Trường thông tin bổ sung 8', N'Trường thông tin bổ sung 8', 0, 0, 1, N'', 180, 38, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'223b264b-4a56-4d11-88ed-bbba0873c6cc', N'HHDV 9', N'DonGia', N'Đơn giá', N'Đơn giá', 2, 2, 2, N'', 130, 9, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'26f5eff5-99da-42f3-989c-43c2f9c013f2', N'', N'TruongThongTinBoSung10', N'Trường thông tin bổ sung 10', N'Trường thông tin bổ sung 10', 1, 1, 1, N'', NULL, 10, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'2b13e945-3e7d-453d-991b-c13eb8f4c583', N'HHDV 1', N'STT', N'STT', N'STT', 2, 2, 3, N'', 50, 1, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'2d8cc358-c822-43e6-83ff-48ddf6c3c755', N'', N'TruongThongTinBoSung2', N'Trường thông tin bổ sung 2', N'Trường thông tin bổ sung 2', 2, 1, 1, N'', NULL, 2, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'2e7a7d35-3256-4f48-8015-44d7c4f9a1a9', N'HHDV 11', N'ThanhTien', N'Thành tiền', N'Thành tiền', 1, 2, 2, N'', 150, 11, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'2feb3701-180d-428e-bdb5-591c6199d403', N'', N'MauSo', N'Ký hiệu mẫu hóa đơn', N'Ký hiệu mẫu hóa đơn', 0, 0, 1, N'', 180, 4, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'30f7b196-ff39-4301-a7e7-5566b4774b07', N'HHDV 3', N'TenHang', N'Tên hàng', N'Tên hàng hóa, dịch vụ', 2, 2, 1, N'', 170, 3, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'320f0c7a-fb7b-4dc3-b159-cd2223c01c36', N'', N'HinhThucDieuChinh', N'Hình thức điều chỉnh', N'Hình thức điều chỉnh', 0, 0, 1, N'', 150, 17, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'33b43e57-2e68-4186-b5e3-25df73f3ebb6', N'HHDV 26', N'TenNhanVien', N'Tên nhân viên', N'Tên nhân viên', 1, 2, 1, N'', 170, 26, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'346773c4-c97e-44c3-987b-6e61b4832651', N'HHDV 21', N'SoKhung', N'Số khung', N'Số khung', 1, 2, 1, N'', 130, 21, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'3467daf9-cdaf-4f37-ad07-6d01d977e89f', N'', N'ThongTinTao', N'Thông tin tạo', N'Thông tin tạo', 0, 0, 4, N'', 170, 28, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'358bac8e-6bc8-4c4d-8eb7-8f3b063e03fa', N'HHDV 11', N'ThanhTien', N'Thành tiền', N'Thành tiền', 2, 2, 2, N'', 150, 11, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'36cb4f0c-a180-42a9-95de-96fdcbe1cf5c', N'', N'TruongThongTinBoSung6', N'Trường thông tin bổ sung 6', N'Trường thông tin bổ sung 6', 1, 1, 1, N'', NULL, 6, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'379f97d2-f917-4c8d-9dd7-78f94b2349d0', N'HHDV 17', N'TienThueGTGT', N'Tiền thuế GTGT', N'Tiền thuế GTGT', 1, 2, 2, N'', 130, 17, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'3b1cd675-d3cc-4e07-94f6-3afea0f02ed1', N'HHDV 7', N'SoLuong', N'Số lượng', N'Số lượng', 1, 2, 3, N'', 100, 7, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'401721a3-909e-451e-b0f3-2bfdabb3bd9a', N'HHDV 8', N'DonGiaSauThue', N'Đơn giá sau thuế', N'Đơn giá sau thuế', 2, 2, 2, N'', 130, 8, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'4447444d-3bb8-409e-a959-8319fbe8ef66', N'', N'TruongThongTinBoSung6', N'Trường thông tin bổ sung 6', N'Trường thông tin bổ sung 6', 2, 1, 1, N'', NULL, 6, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'4a9b62b3-61e3-4430-8cc2-d8dc990671f1', N'HHDV 35', N'TruongMoRongChiTiet9', N'Trường mở rộng chi tiết số 9', N'Trường mở rộng chi tiết số 9', 2, 2, 1, N'', 170, 35, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'4c882f28-302e-4a5b-9975-46cdb2e5c15f', N'HHDV 24', N'GhiChu', N'Ghi chú', N'Ghi chú', 2, 2, 1, N'', 150, 24, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'52229233-452e-403f-94ee-7775b3b54074', N'', N'TruongThongTinBoSung4', N'Trường thông tin bổ sung 4', N'Trường thông tin bổ sung 4', 1, 1, 1, N'', NULL, 4, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'523f001d-9ac1-4a51-bec5-cbdd03560b06', N'HHDV 7', N'SoLuong', N'Số lượng', N'Số lượng', 2, 2, 3, N'', 100, 7, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'53539319-c292-44db-9678-f512f27e1bb5', N'HHDV 27', N'TruongMoRongChiTiet1', N'Trường mở rộng chi tiết số 1', N'Trường mở rộng chi tiết số 1', 1, 2, 1, N'', 170, 27, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'53eae3fa-5c10-4153-8d05-9bb1f46c2758', N'', N'TruongThongTinBoSung6', N'Trường thông tin bổ sung 6', N'Trường thông tin bổ sung 6', 0, 0, 1, N'', 180, 36, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'55538320-9046-480f-8ed8-fdc7fe5bb841', N'', N'TruongThongTinBoSung7', N'Trường thông tin bổ sung 7', N'Trường thông tin bổ sung 7', 1, 1, 1, N'', NULL, 7, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'555cc165-1806-4c16-bb9f-d54f83951eae', N'', N'TruongThongTinBoSung1', N'Trường thông tin bổ sung 1', N'Trường thông tin bổ sung 1', 0, 0, 1, N'', 180, 31, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'561bded1-dc42-4ead-8e12-cb8987d163f2', N'HHDV 35', N'TruongMoRongChiTiet9', N'Trường mở rộng chi tiết số 9', N'Trường mở rộng chi tiết số 9', 1, 2, 1, N'', 170, 35, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'58b2e6c9-65c3-4e64-9268-d6c0bd05f392', N'', N'LyDoXoaBo', N'Lý do xóa bỏ', N'Lý do xóa bỏ', 0, 0, 1, N'', 150, 26, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'5b4bdf5f-a5eb-4139-8dad-5732e500286f', N'HHDV 13', N'TyLeChietKhau', N'Tỷ lệ chiết khấu', N'Tỷ lệ chiết khấu', 1, 2, 5, N'', 120, 13, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'5d41a015-18c7-4d6f-9fa2-c0fa6df64ecb', N'', N'MaCuaCQT', N'Mã CQT cấp', N'Mã CQT cấp', 0, 0, 1, N'', 200, 3, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'605b743a-1c07-489f-a764-f46df291ad93', N'HHDV 24', N'GhiChu', N'Ghi chú', N'Ghi chú', 1, 2, 1, N'', 150, 24, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'639938f6-44c1-425f-b795-cfd62b13a9f5', N'HHDV 19', N'SoLo', N'Số lô', N'Số lô', 1, 2, 1, N'', 130, 19, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'64b5580c-a02a-473a-ad8b-9c9ef2c54a09', N'HHDV 32', N'TruongMoRongChiTiet6', N'Trường mở rộng chi tiết số 6', N'Trường mở rộng chi tiết số 6', 1, 2, 1, N'', 170, 32, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'654488bf-dd9e-4b5f-8361-643a4db9f763', N'', N'TruongThongTinBoSung1', N'Trường thông tin bổ sung 1', N'Trường thông tin bổ sung 1', 1, 1, 1, N'', NULL, 1, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'68c981d7-c8ea-495c-b383-73ef77ab1d0f', N'', N'MaKhachHang', N'Mã khách hàng', N'Mã khách hàng', 0, 0, 1, N'', 140, 6, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'6a4ac979-d5c6-4745-9b9c-391c9905287f', N'', N'TenNhanVienBanHang', N'NV bán hàng', N'NV bán hàng', 0, 0, 1, N'', 130, 11, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'6b59ac8e-615d-4884-b47e-8443ef0a3b96', N'HHDV 29', N'TruongMoRongChiTiet3', N'Trường mở rộng chi tiết số 3', N'Trường mở rộng chi tiết số 3', 2, 2, 1, N'', 170, 29, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'6c347283-c17d-41e9-9408-3c031b833006', N'HHDV 16', N'ThueGTGT', N'% Thuế GTGT', N'% Thuế GTGT', 1, 2, 5, N'', 100, 16, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'6dd11b3c-f7d6-480b-8eed-2e400c537659', N'HHDV 25', N'MaNhanVien', N'Mã nhân viên', N'Mã nhân viên', 2, 2, 1, N'', 130, 25, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'6ea389e2-9a7b-44e2-b8af-6fa40492e82d', N'HHDV 22', N'SoMay', N'Số máy', N'Số máy', 2, 2, 1, N'', 130, 22, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'72a6b8c5-357b-4078-87b7-9d47895758a9', N'', N'UyNhiemLapHoaDon', N'Ủy nhiệm lập hóa đơn', N'Ủy nhiệm lập hóa đơn', 0, 0, 1, N'', 150, 14, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'75b0a57d-01c0-4d32-8fcd-e76b86dec250', N'', N'TrangThaiThoaThuan', N'Trạng thái thỏa thuận', N'Trạng thái thỏa thuận', 0, 0, 1, N'', 150, 18, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'75b5e3a9-65cf-448a-81b5-0e846c21a4e3', N'', N'TongTienThanhToan', N'Tổng tiền thanh toán', N'Tổng tiền thanh toán', 0, 0, 2, N'', 170, 12, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'76bb37c4-815a-4500-985d-c3cab4884636', N'HHDV 4', N'TinhChat', N'Tính chất', N'Tính chất', 2, 2, 3, N'', 120, 4, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'7aefe5fc-d7ca-4d72-931a-dbc39603dcf1', N'HHDV 28', N'TruongMoRongChiTiet2', N'Trường mở rộng chi tiết số 2', N'Trường mở rộng chi tiết số 2', 1, 2, 1, N'', 170, 28, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'7db5f081-d72e-47d7-8573-0e1c418ee64c', N'HHDV 6', N'DonViTinh', N'ĐVT', N'ĐVT', 2, 2, 1, N'', 100, 6, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'8070fb84-a255-4bc4-a87c-2346f2c192ae', N'HHDV 23', N'XuatBanPhi', N'Xuất bản phí', N'Xuất bản phí', 1, 2, 1, N'', 130, 23, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'8093a301-2347-44f5-a2f7-4485c623125a', N'', N'TaiLieuDinhKem', N'Đính kèm', N'Đính kèm', 0, 0, 1, N'', 150, 30, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'80ec32d9-03c4-43f5-acec-476a4722713a', N'', N'TrangThai', N'Trạng thái hóa đơn', N'Trạng thái hóa đơn', 0, 0, 1, N'', 150, 16, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'8373c33a-f952-409f-9c90-5f66b1ff9222', N'HHDV 20', N'HanSuDung', N'Hạn sử dụng', N'Hạn sử dụng', 2, 2, 4, N'', 130, 20, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'87adf1f6-b126-4f1b-9401-c15fb80e6aca', N'', N'HoTenNguoiMuaHang', N'Người mua hàng', N'Người mua hàng', 0, 0, 1, N'', 150, 10, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'880c58ef-9cca-4906-bc54-a02a3386d30e', N'', N'TruongThongTinBoSung7', N'Trường thông tin bổ sung 7', N'Trường thông tin bổ sung 7', 0, 0, 1, N'', 180, 37, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'88ab98f2-c69b-40c4-bd36-736d171439c9', N'', N'HoTenNguoiNhanHD', N'Tên người nhận', N'Tên người nhận', 0, 0, 1, N'', 180, 22, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'8a8fcf5c-8709-4737-9bd2-f375d8d4a030', N'HHDV 14', N'TienChietKhau', N'Tiền chiết khấu', N'Tiền chiết khấu', 1, 2, 2, N'', 130, 14, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'9592b1cd-2fa8-465a-a28b-92106e04bce5', N'', N'TruongThongTinBoSung4', N'Trường thông tin bổ sung 4', N'Trường thông tin bổ sung 4', 2, 1, 1, N'', NULL, 4, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'96b42ad7-6a22-4b28-84d2-c91b912bb6f9', N'', N'TruongThongTinBoSung3', N'Trường thông tin bổ sung 3', N'Trường thông tin bổ sung 3', 1, 1, 1, N'', NULL, 3, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'990f5ce0-6160-4053-b576-4c2fac648020', N'', N'TrangThaiQuyTrinh', N'Trạng thái quy trình', N'Trạng thái quy trình', 0, 0, 1, N'', 150, 19, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'9912148a-023d-4085-a099-4190d3d7494e', N'HHDV 28', N'TruongMoRongChiTiet2', N'Trường mở rộng chi tiết số 2', N'Trường mở rộng chi tiết số 2', 2, 2, 1, N'', 170, 28, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'9984df34-d38a-493b-af08-3e0be2388a52', N'HHDV 30', N'TruongMoRongChiTiet4', N'Trường mở rộng chi tiết số 4', N'Trường mở rộng chi tiết số 4', 2, 2, 1, N'', 170, 30, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'99e663d9-9455-4744-85fb-088531ef03ea', N'', N'TrangThaiGuiHoaDon', N'Trạng thái gửi hóa đơn', N'Trạng thái gửi hóa đơn', 0, 0, 1, N'', 170, 21, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'9aa46023-ab42-4d82-92d4-97484f5bb399', N'HHDV 10', N'ThanhTienSauThue', N'Thành tiền sau thuế', N'Thành tiền sau thuế', 2, 2, 2, N'', 150, 10, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'9db017bd-47fe-4bcd-91b6-5f0fb7a0da1f', N'', N'TruongThongTinBoSung3', N'Trường thông tin bổ sung 3', N'Trường thông tin bổ sung 3', 2, 1, 1, N'', NULL, 3, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'a0d4ba20-6bbb-454d-a1bb-b5c2c1cefe90', N'HHDV 21', N'SoKhung', N'Số khung', N'Số khung', 2, 2, 1, N'', 130, 21, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'a2d062b6-8f35-43fb-a1f4-59a82b5813db', N'HHDV 12', N'ThanhTienQuyDoi', N'Thành tiền quy đổi', N'Thành tiền quy đổi', 1, 2, 2, N'', 150, 12, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'a92f567e-b038-49b8-9738-b8b71bc90ac3', N'HHDV 30', N'TruongMoRongChiTiet4', N'Trường mở rộng chi tiết số 4', N'Trường mở rộng chi tiết số 4', 1, 2, 1, N'', 170, 30, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'ad86061b-fa83-45a3-a10a-5044485a17fa', N'HHDV 2', N'MaHang', N'Mã hàng', N'Mã hàng', 2, 2, 1, N'', 130, 2, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'adcf1e1c-5f00-4c59-9060-8d8120ce41b2', N'HHDV 12', N'ThanhTienQuyDoi', N'Thành tiền quy đổi', N'Thành tiền quy đổi', 2, 2, 2, N'', 150, 12, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'aef4d8ed-0667-4093-b9ee-6d4df3627270', N'', N'SoLanChuyenDoi', N'Số lần chuyển thành hóa đơn giấy', N'Số lần chuyển đổi', 0, 0, 3, N'', 150, 25, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'b0e89374-56db-4875-8ff8-f60e041815e2', N'', N'TruongThongTinBoSung5', N'Trường thông tin bổ sung 5', N'Trường thông tin bổ sung 5', 0, 0, 1, N'', 180, 35, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'b0f6f8b5-4891-4061-832c-902acb75202a', N'', N'LoaiChungTu', N'Loại chứng từ', N'Loại chứng từ', 0, 0, 1, N'', 150, 27, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'b128c123-0dce-4dad-aa6c-42805486cf05', N'HHDV 31', N'TruongMoRongChiTiet5', N'Trường mở rộng chi tiết số 5', N'Trường mở rộng chi tiết số 5', 1, 2, 1, N'', 170, 31, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'b14209a4-dabf-42dd-9184-85befc3b6316', N'HHDV 18', N'TienThueGTGTQuyDoi', N'Tiền thuế GTGT quy đổi', N'Tiền thuế GTGT quy đổi', 1, 2, 2, N'', 150, 18, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'b3c80be4-e10e-4ac0-b80c-32e62c0c4438', N'', N'KyHieu', N'Ký hiệu hóa đơn', N'Ký hiệu hóa đơn', 0, 0, 1, N'', 150, 5, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'b63226bc-1534-41a9-bc9b-ab7452863898', N'', N'EmailNguoiNhanHD', N'Email người nhận', N'Email người nhận', 0, 0, 1, N'', 180, 23, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'b79b3c4c-86c4-42c5-adab-5624888e5872', N'HHDV 5', N'MaQuyCach', N'Mã quy cách', N'Mã quy cách', 1, 2, 1, N'', 100, 5, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'b986cc74-7676-4f02-8d0f-8a431e22acf4', N'HHDV 4', N'TinhChat', N'Tính chất', N'Tính chất', 1, 2, 3, N'', 120, 4, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'b9f2c3f6-f2a5-4102-8440-16842515bde2', N'', N'TruongThongTinBoSung2', N'Trường thông tin bổ sung 2', N'Trường thông tin bổ sung 2', 1, 1, 1, N'', NULL, 2, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'ba5018d9-a6a5-4432-bae9-1689ef2c3dd3', N'', N'TruongThongTinBoSung5', N'Trường thông tin bổ sung 5', N'Trường thông tin bổ sung 5', 1, 1, 1, N'', NULL, 5, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'bcf3ca2c-126c-493e-929b-9ea150733eea', N'', N'TruongThongTinBoSung10', N'Trường thông tin bổ sung 10', N'Trường thông tin bổ sung 10', 0, 0, 1, N'', 180, 40, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'be135e19-f74d-439a-a478-1e92725f48b3', N'', N'HinhThucHoaDon', N'Hình thức hóa đơn', N'Hình thức hóa đơn', 0, 0, 1, N'', 150, 13, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'c1b0007a-deff-4e30-a255-620379670ba2', N'HHDV 3', N'TenHang', N'Tên hàng', N'Tên hàng hóa, dịch vụ', 1, 2, 1, N'', 170, 3, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'c39f6ad8-369c-4acf-9bd2-45d4de36bbc2', N'HHDV 23', N'XuatBanPhi', N'Xuất bản phí', N'Xuất bản phí', 2, 2, 1, N'', 130, 23, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'c43e2f87-e68f-437c-b3af-03ae6ae49398', N'HHDV 34', N'TruongMoRongChiTiet8', N'Trường mở rộng chi tiết số 8', N'Trường mở rộng chi tiết số 8', 1, 2, 1, N'', 170, 34, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'c52ccfa5-5619-41aa-9094-2debe9db7b02', N'HHDV 31', N'TruongMoRongChiTiet5', N'Trường mở rộng chi tiết số 5', N'Trường mở rộng chi tiết số 5', 2, 2, 1, N'', 170, 31, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'c5d652c5-aee8-44ec-b8e7-cfd8692f9572', N'', N'TruongThongTinBoSung8', N'Trường thông tin bổ sung 8', N'Trường thông tin bổ sung 8', 2, 1, 1, N'', NULL, 8, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'c75610d8-dd1a-44d9-b853-1d5d49f57cc5', N'', N'SoHoaDon', N'Số hóa đơn', N'Số hóa đơn', 0, 0, 1, N'', 130, 2, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'c7e8a6d7-3e1d-4e8e-b193-570c6a7c0232', N'', N'TruongThongTinBoSung7', N'Trường thông tin bổ sung 7', N'Trường thông tin bổ sung 7', 2, 1, 1, N'', NULL, 7, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'c7ea3612-8e82-4ea4-b2ec-b6c6538bcdc8', N'HHDV 26', N'TenNhanVien', N'Tên nhân viên', N'Tên nhân viên', 2, 2, 1, N'', 170, 26, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'c9c6b891-d3e9-4adc-9c8e-01fc9a0f55e9', N'', N'TruongThongTinBoSung9', N'Trường thông tin bổ sung 9', N'Trường thông tin bổ sung 9', 2, 1, 1, N'', NULL, 9, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'cc017e63-cfaa-4990-b921-df27b47327dc', N'HHDV 20', N'HanSuDung', N'Hạn sử dụng', N'Hạn sử dụng', 1, 2, 4, N'', 130, 20, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'cd302f42-b0b9-4d04-9849-7a9da4d72e76', N'HHDV 10', N'ThanhTienSauThue', N'Thành tiền sau thuế', N'Thành tiền sau thuế', 1, 2, 2, N'', 150, 10, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'ce112e90-1ffc-4bea-8761-4dee46dd479b', N'HHDV 29', N'TruongMoRongChiTiet3', N'Trường mở rộng chi tiết số 3', N'Trường mở rộng chi tiết số 3', 1, 2, 1, N'', 170, 29, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'cf4c24c0-0f0e-49c5-a0ae-632ed7ba5280', N'HHDV 27', N'TruongMoRongChiTiet1', N'Trường mở rộng chi tiết số 1', N'Trường mở rộng chi tiết số 1', 2, 2, 1, N'', 170, 27, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'd04a1a55-dd58-4c8f-a51a-fd9a168e40f9', N'HHDV 36', N'TruongMoRongChiTiet10', N'Trường mở rộng chi tiết số 10', N'Trường mở rộng chi tiết số 10', 2, 2, 1, N'', 170, 36, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'd0a746d6-a595-47e3-aba1-72d68a99cddf', N'', N'LoaiHoaDon', N'Loại hóa đơn', N'Loại hóa đơn', 0, 0, 1, N'', 150, 15, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'd2e4b1da-5b87-4228-8b10-148d9eb0b791', N'HHDV 25', N'MaNhanVien', N'Mã nhân viên', N'Mã nhân viên', 1, 2, 1, N'', 130, 25, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'd638b692-19f2-481e-8025-b4748773585f', N'', N'TruongThongTinBoSung2', N'Trường thông tin bổ sung 2', N'Trường thông tin bổ sung 2', 0, 0, 1, N'', 180, 32, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'dce4c5bd-29a5-4505-9760-5f8f57e83b92', N'', N'TruongThongTinBoSung4', N'Trường thông tin bổ sung 4', N'Trường thông tin bổ sung 4', 0, 0, 1, N'', 180, 34, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'dd49d5dd-226b-4340-bbca-a58aaa39a3d8', N'HHDV 36', N'TruongMoRongChiTiet10', N'Trường mở rộng chi tiết số 10', N'Trường mở rộng chi tiết số 10', 1, 2, 1, N'', 170, 36, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'de71da2c-8bcf-4330-a66f-4fcf1c5ddf68', N'', N'NgayHoaDon', N'Ngày hóa đơn', N'Ngày hóa đơn', 0, 0, 4, N'', 120, 1, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'de9d82d0-c1e1-4a49-b7fa-4dedb28f2741', N'HHDV 15', N'TienChietKhauQuyDoi', N'Tiền chiết khấu quy đổi', N'Tiền chiết khấu quy đổi', 2, 2, 2, N'', 140, 15, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'e3bc4900-c57c-4a9d-a2b0-b9f8bf1b5f17', N'', N'MaSoThue', N'Mã số thuế', N'Mã số thuế', 0, 0, 1, N'', 130, 9, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'e84b53e6-a9a1-4ffe-b8d8-9397014858c6', N'HHDV 13', N'TyLeChietKhau', N'Tỷ lệ chiết khấu', N'Tỷ lệ chiết khấu', 2, 2, 5, N'', 120, 13, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'e875c6af-7e1b-4746-9b5b-bd46c57f8212', N'HHDV 9', N'DonGia', N'Đơn giá', N'Đơn giá', 1, 2, 2, N'', 130, 9, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'ed9cdfae-2591-4851-b6d8-d992521f1a08', N'', N'SoDienThoaiNguoiNhanHD', N'Số điện thoại người nhận', N'Số điện thoại người nhận', 0, 0, 1, N'', 180, 24, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'eea4442d-397e-4fab-92fb-048475f651ff', N'HHDV 5', N'MaQuyCach', N'Mã quy cách', N'Mã quy cách', 2, 2, 1, N'', 100, 5, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'ef62dab2-15f4-4c71-8968-422d037090a1', N'', N'ThongTinCapNhat', N'Thông tin cập nhật', N'Thông tin cập nhật', 0, 0, 1, N'', 170, 29, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'f234dd87-4690-4ab5-af70-5316a0b0c84c', N'HHDV 34', N'TruongMoRongChiTiet8', N'Trường mở rộng chi tiết số 8', N'Trường mở rộng chi tiết số 8', 2, 2, 1, N'', 170, 34, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'f25c2caf-ecc1-4b23-ac65-066586791ac5', N'', N'TruongThongTinBoSung8', N'Trường thông tin bổ sung 8', N'Trường thông tin bổ sung 8', 1, 1, 1, N'', NULL, 8, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'f8e35579-8adc-42f8-adf1-a192eaa5fe76', N'', N'TruongThongTinBoSung5', N'Trường thông tin bổ sung 5', N'Trường thông tin bổ sung 5', 2, 1, 1, N'', NULL, 5, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'f9d2eae4-9eb4-4508-a94f-265d44e2e681', N'HHDV 32', N'TruongMoRongChiTiet6', N'Trường mở rộng chi tiết số 6', N'Trường mở rộng chi tiết số 6', 2, 2, 1, N'', 170, 32, 0, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'fc411786-5e19-4437-9ac3-4c5b12d1855e', N'HHDV 6', N'DonViTinh', N'ĐVT', N'ĐVT', 1, 2, 1, N'', 100, 6, 1, NULL, NULL)
                GO
                INSERT [dbo].[ThietLapTruongDuLieus] ([ThietLapTruongDuLieuId], [MaTruong], [TenCot], [TenTruong], [TenTruongHienThi], [LoaiHoaDon], [LoaiTruongDuLieu], [KieuDuLieu], [GhiChu], [DoRong], [STT], [HienThi], [GiaTri], [BoKyHieuHoaDonId]) VALUES (N'fdc9131f-8e23-4ee4-8ebc-9b56aa965fec', N'HHDV 2', N'MaHang', N'Mã hàng', N'Mã hàng', 1, 2, 1, N'', 130, 2, 1, NULL, NULL)
                GO
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
