using Microsoft.EntityFrameworkCore.Migrations;

namespace DLL.Migrations
{
    public partial class filldatatodefaultsetup : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "TruongDuLieus",
                column: "DefaultSTT",
                values: new object[] {
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                    26,
                    27,
                    28,
                    29,
                    30,
                    31,
                    32,
                    33,
                    34,
                    35,
                    36,
                    37,
                    38,
                    39,
                    40,
                    41,
                    42,
                    43,
                    44,
                    45,
                    46,
                    47,
                    48,
                    49
                },
                keyColumn: "MaTruong",
                keyValues: new object[]
                {
                    "stt",
                    "ngayHoaDon",
                    "soHoaDon",
                    "mauSoHoaDon",
                    "kyHieuHoaDon",
                    "maKhachHang",
                    "tenKhachHang",
                    "diaChi",
                    "maSoThue",
                    "nguoiMuaHang",
                    "hinhThucThanhToan",
                    "loaiTien",
                    "tyGia",
                    "maHang",
                    "tenHang",
                    "donViTinh",
                    "soLuong",
                    "donGiaSauThue",
                    "donGia",
                    "thanhTienSauThue",
                    "thanhTien",
                    "thanhTienQuyDoi",
                    "tyLeChietKhau",
                    "tienChietKhau",
                    "tienChietKhauQuyDoi",
                    "doanhSoBanChuaThue",
                    "doanhSoBanChuaThueQuyDoi",
                    "thueGTGT",
                    "tienThueGTGT",
                    "tienThueGTGTQuyDoi",
                    "tongTienThanhToan",
                    "tongTienThanhToanQuyDoi",
                    "hangKhuyenMai",
                    "maQuyCach",
                    "soLo",
                    "hanSuDung",
                    "soKhung",
                    "soMay",
                    "xuatBanPhi",
                    "ghiChu",
                    "maNhanVien",
                    "tenNhanVien",
                    "loaiHoaDon",
                    "trangThaiHoaDon",
                    "trangThaiPhatHanh",
                    "maTraCuu",
                    "lyDoXoaBo",
                    "ngayLap",
                    "nguoiLap"
                });

            migrationBuilder.UpdateData(
                table: "TruongDuLieus",
                column: "DinhDangSo",
                values: new object[] {
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                    true,
                },
                keyColumn: "MaTruong",
                keyValues: new object[]
                {
                    "tyGia",
                    "donGiaSauThue",
                    "donGia",
                    "thanhTienSauThue",
                    "thanhTien",
                    "thanhTienQuyDoi",
                    "tienChietKhau",
                    "tienChietKhauQuyDoi",
                    "doanhSoBanChuaThue",
                    "doanhSoBanChuaThueQuyDoi",
                    "tienThueGTGT",
                    "tienThueGTGTQuyDoi",
                    "tongTienThanhToan",
                    "tongTienThanhToanQuyDoi",
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
