// <auto-generated />
using System;
using DLL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DLL.Migrations
{
    [DbContext(typeof(Datacontext))]
    [Migration("20211114090454_add-du-lieu-thiet-lap-truong-du-lieu")]
    partial class adddulieuthietlaptruongdulieu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DLL.Entity.BaoCao.BaoCaoTinhHinhSuDungHoaDon", b =>
                {
                    b.Property<string>("BaoCaoTinhHinhSuDungHoaDonId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DenNgay");

                    b.Property<string>("DienGiai");

                    b.Property<int>("Nam");

                    b.Property<DateTime>("NgayLap");

                    b.Property<string>("NguoiLapId");

                    b.Property<int?>("Quy");

                    b.Property<string>("TenNguoiDaiDienPhapLuat");

                    b.Property<string>("TenNguoiLap");

                    b.Property<int?>("Thang");

                    b.Property<DateTime>("TuNgay");

                    b.HasKey("BaoCaoTinhHinhSuDungHoaDonId");

                    b.ToTable("BaoCaoTinhHinhSuDungHoaDons");
                });

            modelBuilder.Entity("DLL.Entity.BaoCao.BaoCaoTinhHinhSuDungHoaDonChiTiet", b =>
                {
                    b.Property<string>("BaoCaoTinhHinhSuDungHoaDonChiTietId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BaoCaoTinhHinhSuDungHoaDonId");

                    b.Property<int>("DaHuy");

                    b.Property<int>("DaMat");

                    b.Property<int>("DaSuDung");

                    b.Property<int>("DaXoaBo");

                    b.Property<string>("KyHieu");

                    b.Property<int>("LoaiHoaDon");

                    b.Property<string>("MauSo");

                    b.Property<string>("SoHuy");

                    b.Property<int>("SoLuongTon");

                    b.Property<string>("SoMat");

                    b.Property<string>("SoXoaBo");

                    b.Property<string>("SuDungDen");

                    b.Property<string>("SuDungTu");

                    b.Property<string>("TonCuoiKyDen");

                    b.Property<string>("TonCuoiKyTu");

                    b.Property<string>("TonDauKyDen");

                    b.Property<string>("TonDauKyTu");

                    b.Property<int>("TongSo");

                    b.Property<int>("TongSoSuDung");

                    b.Property<string>("TrongKyDen");

                    b.Property<string>("TrongKyTu");

                    b.HasKey("BaoCaoTinhHinhSuDungHoaDonChiTietId");

                    b.HasIndex("BaoCaoTinhHinhSuDungHoaDonId");

                    b.ToTable("BaoCaoTinhHinhSuDungHoaDonChiTiets");
                });

            modelBuilder.Entity("DLL.Entity.BaoCao.NghiepVu", b =>
                {
                    b.Property<string>("NghiepVuId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TenNghiepVu");

                    b.HasKey("NghiepVuId");

                    b.ToTable("NghiepVus");
                });

            modelBuilder.Entity("DLL.Entity.BaoCao.TruongDuLieu", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Align");

                    b.Property<bool>("Default");

                    b.Property<int>("DefaultSTT");

                    b.Property<bool>("DinhDangSo");

                    b.Property<bool>("HienThiKhiCongGop");

                    b.Property<string>("MaTruong");

                    b.Property<string>("NghiepVuId");

                    b.Property<int>("STT");

                    b.Property<int>("Size");

                    b.Property<bool>("Status");

                    b.Property<string>("TenHienThi");

                    b.Property<string>("TenTruong");

                    b.HasKey("Id");

                    b.HasIndex("NghiepVuId");

                    b.ToTable("TruongDuLieus");
                });

            modelBuilder.Entity("DLL.Entity.Config.ConfigNoiDungEmail", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LoaiEmail");

                    b.Property<string>("NoiDungEmail");

                    b.Property<string>("TieuDeEmail");

                    b.HasKey("Id");

                    b.ToTable("ConfigNoiDungEmails");
                });

            modelBuilder.Entity("DLL.Entity.Config.ThietLapTruongDuLieu", b =>
                {
                    b.Property<string>("ThietLapTruongDuLieuId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DoRong");

                    b.Property<string>("GhiChu");

                    b.Property<bool>("HienThi");

                    b.Property<int>("KieuDuLieu");

                    b.Property<int>("LoaiHoaDon");

                    b.Property<int>("LoaiTruongDuLieu");

                    b.Property<string>("MaTruong");

                    b.Property<int>("STT");

                    b.Property<string>("TenCot");

                    b.Property<string>("TenTruong");

                    b.Property<string>("TenTruongHienThi");

                    b.HasKey("ThietLapTruongDuLieuId");

                    b.ToTable("ThietLapTruongDuLieus");
                });

            modelBuilder.Entity("DLL.Entity.Config.TuyChon", b =>
                {
                    b.Property<string>("Ma")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GiaTri");

                    b.Property<string>("Ten");

                    b.HasKey("Ma");

                    b.ToTable("TuyChons");
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.DoiTuong", b =>
                {
                    b.Property<string>("DoiTuongId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChiNhanh");

                    b.Property<string>("ChucDanh");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("DiaChi");

                    b.Property<string>("EmailNguoiMuaHang");

                    b.Property<string>("EmailNguoiNhanHD");

                    b.Property<string>("HoTenNguoiMuaHang");

                    b.Property<string>("HoTenNguoiNhanHD");

                    b.Property<bool?>("IsKhachHang");

                    b.Property<bool?>("IsNhanVien");

                    b.Property<int?>("LoaiKhachHang");

                    b.Property<string>("Ma");

                    b.Property<string>("MaSoThue");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<int?>("STT");

                    b.Property<string>("SoDienThoaiNguoiMuaHang");

                    b.Property<string>("SoDienThoaiNguoiNhanHD");

                    b.Property<string>("SoTaiKhoanNganHang");

                    b.Property<bool>("Status");

                    b.Property<string>("Ten");

                    b.Property<string>("TenDonVi");

                    b.Property<string>("TenNganHang");

                    b.HasKey("DoiTuongId");

                    b.ToTable("DoiTuongs");
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.DonViTinh", b =>
                {
                    b.Property<string>("DonViTinhId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("MoTa");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<int?>("STT");

                    b.Property<bool>("Status");

                    b.Property<string>("Ten");

                    b.HasKey("DonViTinhId");

                    b.ToTable("DonViTinhs");
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.HangHoaDichVu", b =>
                {
                    b.Property<string>("HangHoaDichVuId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<decimal?>("DonGiaBan");

                    b.Property<string>("DonViTinhId");

                    b.Property<bool?>("IsGiaBanLaDonGiaSauThue");

                    b.Property<string>("Ma");

                    b.Property<string>("MoTa");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<int?>("STT");

                    b.Property<bool>("Status");

                    b.Property<string>("Ten");

                    b.Property<int>("ThueGTGT");

                    b.Property<decimal?>("TyLeChietKhau");

                    b.HasKey("HangHoaDichVuId");

                    b.HasIndex("DonViTinhId");

                    b.ToTable("HangHoaDichVus");
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.HinhThucThanhToan", b =>
                {
                    b.Property<string>("HinhThucThanhToanId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("MoTa");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<int?>("STT");

                    b.Property<bool>("Status");

                    b.Property<string>("Ten");

                    b.HasKey("HinhThucThanhToanId");

                    b.ToTable("HinhThucThanhToans");
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.HoSoHDDT", b =>
                {
                    b.Property<string>("HoSoHDDTId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChiNhanh");

                    b.Property<string>("CoQuanThueCapCuc");

                    b.Property<string>("CoQuanThueQuanLy");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("DiaChi");

                    b.Property<string>("EmailLienHe");

                    b.Property<string>("EmailNguoiDaiDienPhapLuat");

                    b.Property<string>("Fax");

                    b.Property<string>("HoTenNguoiDaiDienPhapLuat");

                    b.Property<string>("MaSoThue");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("NganhNgheKinhDoanhChinh");

                    b.Property<string>("PhuongPhapTinhThueGTGT");

                    b.Property<int?>("STT");

                    b.Property<string>("SoDienThoaiLienHe");

                    b.Property<string>("SoDienThoaiNguoiDaiDienPhapLuat");

                    b.Property<string>("SoTaiKhoanNganHang");

                    b.Property<bool>("Status");

                    b.Property<string>("TenDonVi");

                    b.Property<string>("TenNganHang");

                    b.Property<string>("Website");

                    b.HasKey("HoSoHDDTId");

                    b.ToTable("HoSoHDDTs");
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.LoaiTien", b =>
                {
                    b.Property<string>("LoaiTienId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("Ma");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<int?>("STT");

                    b.Property<int?>("SapXep");

                    b.Property<bool>("Status");

                    b.Property<string>("Ten");

                    b.Property<decimal?>("TyGiaQuyDoi");

                    b.HasKey("LoaiTienId");

                    b.ToTable("LoaiTiens");
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.MauHoaDon", b =>
                {
                    b.Property<string>("MauHoaDonId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int>("HinhThucHoaDon");

                    b.Property<string>("KyHieu");

                    b.Property<int>("LoaiHoaDon");

                    b.Property<int>("LoaiKhoGiay");

                    b.Property<int>("LoaiMauHoaDon");

                    b.Property<int>("LoaiNgonNgu");

                    b.Property<int>("LoaiThueGTGT");

                    b.Property<string>("MauSo");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<DateTime?>("NgayKy");

                    b.Property<int>("QuyDinhApDung");

                    b.Property<int?>("STT");

                    b.Property<int?>("SoThuTu");

                    b.Property<bool>("Status");

                    b.Property<string>("Ten");

                    b.Property<string>("TenBoMau");

                    b.Property<int>("UyNhiemLapHoaDon");

                    b.HasKey("MauHoaDonId");

                    b.ToTable("MauHoaDons");
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.MauHoaDonThietLapMacDinh", b =>
                {
                    b.Property<string>("MauHoaDonThietLapMacDinhId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("GiaTri");

                    b.Property<string>("GiaTriBoSung");

                    b.Property<int>("Loai");

                    b.Property<string>("MauHoaDonId");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<int?>("STT");

                    b.Property<bool>("Status");

                    b.HasKey("MauHoaDonThietLapMacDinhId");

                    b.HasIndex("MauHoaDonId");

                    b.ToTable("MauHoaDonThietLapMacDinhs");
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.MauHoaDonTuyChinhChiTiet", b =>
                {
                    b.Property<string>("MauHoaDonTuyChinhChiTietId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("Checked");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("CustomKey");

                    b.Property<bool?>("Disabled");

                    b.Property<int?>("DoRong");

                    b.Property<string>("GiaTri");

                    b.Property<string>("GiaTriMacDinh");

                    b.Property<bool?>("IsParent");

                    b.Property<int>("KieuDuLieuThietLap");

                    b.Property<int>("Loai");

                    b.Property<int>("LoaiChiTiet");

                    b.Property<int>("LoaiContainer");

                    b.Property<string>("MauHoaDonId");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<int?>("STT");

                    b.Property<bool>("Status");

                    b.Property<string>("TenTiengAnh");

                    b.Property<string>("TuyChinhChiTiet");

                    b.HasKey("MauHoaDonTuyChinhChiTietId");

                    b.HasIndex("MauHoaDonId");

                    b.ToTable("MauHoaDonTuyChinhChiTiets");
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.QuyetDinhApDungHoaDon", b =>
                {
                    b.Property<string>("QuyetDinhApDungHoaDonId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CanCuDeBanHanhQuyetDinh");

                    b.Property<string>("ChucDanh");

                    b.Property<string>("CoQuanThue");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("Dieu1");

                    b.Property<string>("Dieu2");

                    b.Property<string>("Dieu3");

                    b.Property<string>("Dieu4");

                    b.Property<int?>("Dieu5");

                    b.Property<bool?>("HasChungThuSo");

                    b.Property<bool?>("HasMayIn");

                    b.Property<bool?>("HasMayTinh");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<DateTime?>("NgayHieuLuc");

                    b.Property<DateTime?>("NgayQuyetDinh");

                    b.Property<string>("NguoiDaiDienPhapLuat");

                    b.Property<string>("NoiDungDieu3");

                    b.Property<string>("NoiDungDieu4");

                    b.Property<int?>("STT");

                    b.Property<string>("SoQuyetDinh");

                    b.Property<bool>("Status");

                    b.HasKey("QuyetDinhApDungHoaDonId");

                    b.ToTable("QuyetDinhApDungHoaDons");
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.QuyetDinhApDungHoaDonDieu1", b =>
                {
                    b.Property<string>("QuyetDinhApDungHoaDonDieu1Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("Checked");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<bool?>("Disabled");

                    b.Property<string>("GiaTri");

                    b.Property<int>("LoaiDieu1");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("QuyetDinhApDungHoaDonId");

                    b.Property<int?>("STT");

                    b.Property<bool>("Status");

                    b.Property<string>("Ten");

                    b.HasKey("QuyetDinhApDungHoaDonDieu1Id");

                    b.HasIndex("QuyetDinhApDungHoaDonId");

                    b.ToTable("QuyetDinhApDungHoaDonDieu1s");
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.QuyetDinhApDungHoaDonDieu2", b =>
                {
                    b.Property<string>("QuyetDinhApDungHoaDonDieu2Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("MauHoaDonId");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("MucDichSuDung");

                    b.Property<string>("QuyetDinhApDungHoaDonId");

                    b.Property<int?>("STT");

                    b.Property<bool>("Status");

                    b.HasKey("QuyetDinhApDungHoaDonDieu2Id");

                    b.HasIndex("QuyetDinhApDungHoaDonId");

                    b.ToTable("QuyetDinhApDungHoaDonDieu2s");
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.TaiLieuDinhKem", b =>
                {
                    b.Property<string>("TaiLieuDinhKemId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int>("LoaiNghiepVu");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("NghiepVuId");

                    b.Property<int?>("STT");

                    b.Property<bool>("Status");

                    b.Property<string>("TenGoc");

                    b.Property<string>("TenGuid");

                    b.HasKey("TaiLieuDinhKemId");

                    b.ToTable("TaiLieuDinhKems");
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.ThongBaoDieuChinhThongTinHoaDon", b =>
                {
                    b.Property<string>("ThongBaoDieuChinhThongTinHoaDonId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CoQuanThue");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("DiaChiCu");

                    b.Property<string>("DiaChiMoi");

                    b.Property<string>("DienThoaiCu");

                    b.Property<string>("DienThoaiMoi");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<DateTime?>("NgayThongBaoDieuChinh");

                    b.Property<DateTime?>("NgayThongBaoPhatHanh");

                    b.Property<int?>("STT");

                    b.Property<string>("So");

                    b.Property<bool>("Status");

                    b.Property<string>("TenDonViCu");

                    b.Property<string>("TenDonViMoi");

                    b.Property<int>("TrangThaiHieuLuc");

                    b.HasKey("ThongBaoDieuChinhThongTinHoaDonId");

                    b.ToTable("ThongBaoDieuChinhThongTinHoaDons");
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.ThongBaoDieuChinhThongTinHoaDonChiTiet", b =>
                {
                    b.Property<string>("ThongBaoDieuChinhThongTinHoaDonChiTietId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("MauHoaDonId");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<int?>("STT");

                    b.Property<bool>("Status");

                    b.Property<string>("ThongBaoDieuChinhThongTinHoaDonId");

                    b.HasKey("ThongBaoDieuChinhThongTinHoaDonChiTietId");

                    b.HasIndex("MauHoaDonId");

                    b.HasIndex("ThongBaoDieuChinhThongTinHoaDonId");

                    b.ToTable("ThongBaoDieuChinhThongTinHoaDonChiTiets");
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.ThongBaoKetQuaHuyHoaDon", b =>
                {
                    b.Property<string>("ThongBaoKetQuaHuyHoaDonId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CoQuanThue");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<DateTime?>("NgayGioHuy");

                    b.Property<DateTime?>("NgayThongBao");

                    b.Property<string>("PhuongPhapHuy");

                    b.Property<int?>("STT");

                    b.Property<string>("So");

                    b.Property<bool>("Status");

                    b.Property<int>("TrangThaiNop");

                    b.HasKey("ThongBaoKetQuaHuyHoaDonId");

                    b.ToTable("ThongBaoKetQuaHuyHoaDons");
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.ThongBaoKetQuaHuyHoaDonChiTiet", b =>
                {
                    b.Property<string>("ThongBaoKetQuaHuyHoaDonChiTietId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("DenSo");

                    b.Property<int>("LoaiHoaDon");

                    b.Property<string>("MauHoaDonId");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<int?>("STT");

                    b.Property<int?>("SoLuong");

                    b.Property<bool>("Status");

                    b.Property<string>("ThongBaoKetQuaHuyHoaDonId");

                    b.Property<int?>("TuSo");

                    b.HasKey("ThongBaoKetQuaHuyHoaDonChiTietId");

                    b.HasIndex("MauHoaDonId");

                    b.HasIndex("ThongBaoKetQuaHuyHoaDonId");

                    b.ToTable("ThongBaoKetQuaHuyHoaDonChiTiets");
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.ThongBaoPhatHanh", b =>
                {
                    b.Property<string>("ThongBaoPhatHanhId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CoQuanThue");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("DienThoai");

                    b.Property<bool?>("IsXacNhan");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<DateTime>("Ngay");

                    b.Property<string>("NguoiDaiDienPhapLuat");

                    b.Property<int?>("STT");

                    b.Property<string>("So");

                    b.Property<bool>("Status");

                    b.Property<int>("TrangThaiNop");

                    b.HasKey("ThongBaoPhatHanhId");

                    b.ToTable("ThongBaoPhatHanhs");
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.ThongBaoPhatHanhChiTiet", b =>
                {
                    b.Property<string>("ThongBaoPhatHanhChiTietId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("DenSo");

                    b.Property<string>("KyHieu");

                    b.Property<string>("MauHoaDonId");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<DateTime?>("NgayBatDauSuDung");

                    b.Property<int?>("STT");

                    b.Property<int?>("SoLuong");

                    b.Property<bool>("Status");

                    b.Property<string>("ThongBaoPhatHanhId");

                    b.Property<int?>("TuSo");

                    b.HasKey("ThongBaoPhatHanhChiTietId");

                    b.HasIndex("MauHoaDonId");

                    b.HasIndex("ThongBaoPhatHanhId");

                    b.ToTable("ThongBaoPhatHanhChiTiets");
                });

            modelBuilder.Entity("DLL.Entity.FileData", b =>
                {
                    b.Property<string>("FileDataId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<byte[]>("Binary");

                    b.Property<string>("Content");

                    b.Property<DateTime>("DateTime");

                    b.Property<int>("Type");

                    b.HasKey("FileDataId");

                    b.ToTable("FileDatas");
                });

            modelBuilder.Entity("DLL.Entity.Function", b =>
                {
                    b.Property<string>("FunctionId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("FunctionName");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("ParentFunctionId");

                    b.Property<int?>("STT");

                    b.Property<bool>("Status");

                    b.Property<string>("SubTitle");

                    b.Property<string>("Title");

                    b.Property<string>("Type");

                    b.HasKey("FunctionId");

                    b.ToTable("Functions");
                });

            modelBuilder.Entity("DLL.Entity.Function_Role", b =>
                {
                    b.Property<string>("FRID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<bool>("Active");

                    b.Property<string>("FunctionId");

                    b.Property<string>("PermissionId");

                    b.Property<string>("RoleId");

                    b.HasKey("FRID");

                    b.HasIndex("FunctionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("Function_Roles");
                });

            modelBuilder.Entity("DLL.Entity.Function_ThaoTac", b =>
                {
                    b.Property<string>("FTID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("FunctionId");

                    b.Property<string>("PermissionId");

                    b.Property<string>("RoleId");

                    b.Property<string>("ThaoTacId");

                    b.Property<string>("UserId");

                    b.HasKey("FTID");

                    b.HasIndex("FunctionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("ThaoTacId");

                    b.HasIndex("UserId");

                    b.ToTable("Function_ThaoTacs");
                });

            modelBuilder.Entity("DLL.Entity.Function_User", b =>
                {
                    b.Property<string>("FUID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("FunctionId");

                    b.Property<string>("PermissionId");

                    b.Property<string>("UserId");

                    b.HasKey("FUID");

                    b.HasIndex("FunctionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("Function_Users");
                });

            modelBuilder.Entity("DLL.Entity.KyKeToan", b =>
                {
                    b.Property<string>("KyKeToanId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<bool?>("DaKhoaNhapSoDuBanDau");

                    b.Property<bool?>("DaKhoaSo");

                    b.Property<DateTime?>("DenNgay");

                    b.Property<string>("GhiChu");

                    b.Property<int?>("LoaiThongTu");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<DateTime?>("NgayChungTu");

                    b.Property<int?>("STT");

                    b.Property<bool>("Status");

                    b.HasKey("KyKeToanId");

                    b.ToTable("KyKeToans");
                });

            modelBuilder.Entity("DLL.Entity.Permission", b =>
                {
                    b.Property<string>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("PermissionName");

                    b.Property<bool?>("Status");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("DLL.Entity.PhanQuyenMauHoaDon", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MauHoaDonId");

                    b.Property<string>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("MauHoaDonId");

                    b.HasIndex("RoleId");

                    b.ToTable("PhanQuyenMauHoaDons");
                });

            modelBuilder.Entity("DLL.Entity.QuanLy.BoKyHieuHoaDon", b =>
                {
                    b.Property<string>("BoKyHieuHoaDonId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int>("HinhThucHoaDon");

                    b.Property<bool?>("IsTuyChinh");

                    b.Property<string>("KyHieu");

                    b.Property<string>("KyHieu1");

                    b.Property<string>("KyHieu23");

                    b.Property<string>("KyHieu4");

                    b.Property<string>("KyHieu56");

                    b.Property<string>("KyHieuHoaDon");

                    b.Property<int>("KyHieuMauSoHoaDon");

                    b.Property<int>("LoaiHoaDon");

                    b.Property<string>("MauHoaDonId");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<int?>("STT");

                    b.Property<int?>("SoBatDau");

                    b.Property<int?>("SoLonNhatDaLapDenHienTai");

                    b.Property<int?>("SoToiDa");

                    b.Property<bool>("Status");

                    b.Property<string>("ThongDiepChungId");

                    b.Property<string>("ThongDiepId");

                    b.Property<int>("TrangThaiSuDung");

                    b.Property<int>("UyNhiemLapHoaDon");

                    b.HasKey("BoKyHieuHoaDonId");

                    b.HasIndex("MauHoaDonId");

                    b.HasIndex("ThongDiepChungId");

                    b.ToTable("BoKyHieuHoaDons");
                });

            modelBuilder.Entity("DLL.Entity.QuanLy.NhatKyXacThucBoKyHieu", b =>
                {
                    b.Property<string>("NhatKyXacThucBoKyHieuId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BoKyHieuHoaDonId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<bool?>("IsHetSoLuongHoaDon");

                    b.Property<string>("MaThongDiepGui");

                    b.Property<string>("MauHoaDonId");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("NoiDung");

                    b.Property<int?>("STT");

                    b.Property<int?>("SoLuongHoaDon");

                    b.Property<string>("SoSeriChungThu");

                    b.Property<bool>("Status");

                    b.Property<string>("TenMauHoaDon");

                    b.Property<string>("TenNguoiXacThuc");

                    b.Property<string>("TenToChucChungThuc");

                    b.Property<DateTime?>("ThoiDiemChapNhan");

                    b.Property<DateTime?>("ThoiGianSuDungDen");

                    b.Property<DateTime?>("ThoiGianSuDungTu");

                    b.Property<DateTime?>("ThoiGianXacThuc");

                    b.Property<string>("ThongDiepId");

                    b.Property<int>("TrangThaiSuDung");

                    b.HasKey("NhatKyXacThucBoKyHieuId");

                    b.HasIndex("BoKyHieuHoaDonId");

                    b.ToTable("NhatKyXacThucBoKyHieus");
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.BienBanDieuChinh", b =>
                {
                    b.Property<string>("BienBanDieuChinhId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChucVuBenA");

                    b.Property<string>("ChucVuBenB");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("DaiDienBenA");

                    b.Property<string>("DaiDienBenB");

                    b.Property<string>("DiaChiBenA");

                    b.Property<string>("DiaChiBenB");

                    b.Property<string>("FileChuaKy");

                    b.Property<string>("FileDaKy");

                    b.Property<string>("HoaDonBiDieuChinhId");

                    b.Property<string>("HoaDonDieuChinhId");

                    b.Property<string>("LyDoDieuChinh");

                    b.Property<string>("MaSoThueBenA");

                    b.Property<string>("MaSoThueBenB");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<DateTime?>("NgayBienBan");

                    b.Property<DateTime?>("NgayKyBenA");

                    b.Property<DateTime?>("NgayKyBenB");

                    b.Property<string>("NoiDungBienBan");

                    b.Property<int?>("STT");

                    b.Property<string>("SoDienThoaiBenA");

                    b.Property<string>("SoDienThoaiBenB");

                    b.Property<bool>("Status");

                    b.Property<string>("TenDonViBenA");

                    b.Property<string>("TenDonViBenB");

                    b.Property<int?>("TrangThaiBienBan");

                    b.Property<string>("XMLChuaKy");

                    b.Property<string>("XMLDaKy");

                    b.HasKey("BienBanDieuChinhId");

                    b.HasIndex("HoaDonBiDieuChinhId");

                    b.HasIndex("HoaDonDieuChinhId");

                    b.ToTable("BienBanDieuChinhs");
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.BienBanXoaBo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChucVu");

                    b.Property<string>("ChucVuBenA");

                    b.Property<string>("DaiDien");

                    b.Property<string>("DaiDienBenA");

                    b.Property<string>("DiaChi");

                    b.Property<string>("DiaChiBenA");

                    b.Property<string>("EmailNguoiNhan");

                    b.Property<string>("FileChuaKy");

                    b.Property<string>("FileDaKy");

                    b.Property<string>("HoaDonDienTuId");

                    b.Property<string>("KhachHangId");

                    b.Property<string>("LyDoXoaBo");

                    b.Property<string>("MaSoThue");

                    b.Property<string>("MaSoThueBenA");

                    b.Property<DateTime?>("NgayBienBan");

                    b.Property<DateTime?>("NgayKyBenA");

                    b.Property<DateTime?>("NgayKyBenB");

                    b.Property<string>("SoBienBan");

                    b.Property<string>("SoDienThoai");

                    b.Property<string>("SoDienThoaiBenA");

                    b.Property<string>("SoDienThoaiNguoiNhan");

                    b.Property<string>("TenCongTyBenA");

                    b.Property<string>("TenKhachHang");

                    b.Property<string>("TenNguoiNhan");

                    b.Property<string>("ThongTu");

                    b.Property<string>("XMLChuaKy");

                    b.Property<string>("XMLDaKy");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonDienTuId");

                    b.HasIndex("KhachHangId");

                    b.ToTable("BienBanXoaBos");
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.HoaDonDienTu", b =>
                {
                    b.Property<string>("HoaDonDienTuId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BoKyHieuHoaDonId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<bool?>("DaGuiThongBaoXoaBoHoaDon");

                    b.Property<string>("DiaChi");

                    b.Property<string>("DiaChiGiaoHang");

                    b.Property<string>("DieuChinhChoHoaDonId");

                    b.Property<string>("EmailNguoiMuaHang");

                    b.Property<string>("EmailNguoiNhanHD");

                    b.Property<string>("FileChuaKy");

                    b.Property<string>("FileDaKy");

                    b.Property<string>("HinhThucThanhToanId");

                    b.Property<string>("HoTenNguoiMuaHang");

                    b.Property<string>("HoTenNguoiNhanHD");

                    b.Property<bool?>("KhachHangDaNhan");

                    b.Property<string>("KhachHangId");

                    b.Property<string>("KyHieu");

                    b.Property<int>("LoaiChungTu");

                    b.Property<int?>("LoaiDieuChinh");

                    b.Property<int>("LoaiHoaDon");

                    b.Property<string>("LoaiTienId");

                    b.Property<string>("LyDoDieuChinh");

                    b.Property<string>("LyDoThayThe");

                    b.Property<string>("LyDoXoaBo");

                    b.Property<string>("MaCuaCQT");

                    b.Property<string>("MaKhachHang");

                    b.Property<string>("MaNhanVienBanHang");

                    b.Property<string>("MaSoThue");

                    b.Property<string>("MaTraCuu");

                    b.Property<string>("MauHoaDonId");

                    b.Property<string>("MauSo");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<DateTime?>("NgayHoaDon");

                    b.Property<DateTime?>("NgayLap");

                    b.Property<DateTime?>("NgayXoaBo");

                    b.Property<string>("NguoiLapId");

                    b.Property<string>("NhanVienBanHangId");

                    b.Property<int?>("STT");

                    b.Property<string>("SoCTXoaBo");

                    b.Property<string>("SoDienThoaiNguoiMuaHang");

                    b.Property<string>("SoDienThoaiNguoiNhanHD");

                    b.Property<string>("SoHoaDon");

                    b.Property<int?>("SoLanChuyenDoi");

                    b.Property<string>("SoTaiKhoanNganHang");

                    b.Property<bool>("Status");

                    b.Property<string>("TaiLieuDinhKem");

                    b.Property<string>("TenKhachHang");

                    b.Property<string>("TenNganHang");

                    b.Property<string>("TenNhanVienBanHang");

                    b.Property<string>("ThamChieu");

                    b.Property<string>("ThayTheChoHoaDonId");

                    b.Property<DateTime?>("ThoiHanThanhToan");

                    b.Property<decimal?>("TongTienChietKhau");

                    b.Property<decimal?>("TongTienChietKhauQuyDoi");

                    b.Property<decimal?>("TongTienHang");

                    b.Property<decimal?>("TongTienHangQuyDoi");

                    b.Property<decimal?>("TongTienThanhToan");

                    b.Property<decimal?>("TongTienThanhToanQuyDoi");

                    b.Property<decimal?>("TongTienThueGTGT");

                    b.Property<decimal?>("TongTienThueGTGTQuyDoi");

                    b.Property<int?>("TrangThai");

                    b.Property<int>("TrangThaiBienBanXoaBo");

                    b.Property<int?>("TrangThaiGuiHoaDon");

                    b.Property<int?>("TrangThaiPhatHanh");

                    b.Property<string>("TruongThongTinBoSung1");

                    b.Property<string>("TruongThongTinBoSung10");

                    b.Property<string>("TruongThongTinBoSung2");

                    b.Property<string>("TruongThongTinBoSung3");

                    b.Property<string>("TruongThongTinBoSung4");

                    b.Property<string>("TruongThongTinBoSung5");

                    b.Property<string>("TruongThongTinBoSung6");

                    b.Property<string>("TruongThongTinBoSung7");

                    b.Property<string>("TruongThongTinBoSung8");

                    b.Property<string>("TruongThongTinBoSung9");

                    b.Property<decimal?>("TyGia");

                    b.Property<string>("XMLChuaKy");

                    b.Property<string>("XMLDaKy");

                    b.HasKey("HoaDonDienTuId");

                    b.HasIndex("BoKyHieuHoaDonId");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("LoaiTienId");

                    b.HasIndex("MauHoaDonId");

                    b.HasIndex("NguoiLapId");

                    b.HasIndex("NhanVienBanHangId");

                    b.ToTable("HoaDonDienTus");
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.HoaDonDienTuChiTiet", b =>
                {
                    b.Property<string>("HoaDonDienTuChiTietId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<decimal?>("DonGia");

                    b.Property<decimal?>("DonGiaQuyDoi");

                    b.Property<decimal?>("DonGiaSauThue");

                    b.Property<string>("DonViTinhId");

                    b.Property<bool?>("DongChietKhau");

                    b.Property<bool?>("DongMoTa");

                    b.Property<string>("GhiChu");

                    b.Property<DateTime?>("HanSuDung");

                    b.Property<string>("HangHoaDichVuId");

                    b.Property<string>("HoaDonDienTuId");

                    b.Property<string>("MaHang");

                    b.Property<string>("MaNhanVien");

                    b.Property<string>("MaQuyCach");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("NhanVienBanHangId");

                    b.Property<int?>("STT");

                    b.Property<string>("SoKhung");

                    b.Property<string>("SoLo");

                    b.Property<decimal?>("SoLuong");

                    b.Property<string>("SoMay");

                    b.Property<bool>("Status");

                    b.Property<string>("TenHang");

                    b.Property<string>("TenNhanVien");

                    b.Property<decimal?>("ThanhTien");

                    b.Property<decimal?>("ThanhTienQuyDoi");

                    b.Property<decimal?>("ThanhTienSauThue");

                    b.Property<decimal?>("ThanhTienSauThueQuyDoi");

                    b.Property<string>("ThueGTGT");

                    b.Property<decimal?>("TienChietKhau");

                    b.Property<decimal?>("TienChietKhauQuyDoi");

                    b.Property<decimal?>("TienThueGTGT");

                    b.Property<decimal?>("TienThueGTGTQuyDoi");

                    b.Property<int>("TinhChat");

                    b.Property<decimal?>("TongTienThanhToan");

                    b.Property<decimal?>("TongTienThanhToanQuyDoi");

                    b.Property<string>("TruongMoRongChiTiet1");

                    b.Property<string>("TruongMoRongChiTiet10");

                    b.Property<string>("TruongMoRongChiTiet2");

                    b.Property<string>("TruongMoRongChiTiet3");

                    b.Property<string>("TruongMoRongChiTiet4");

                    b.Property<string>("TruongMoRongChiTiet5");

                    b.Property<string>("TruongMoRongChiTiet6");

                    b.Property<string>("TruongMoRongChiTiet7");

                    b.Property<string>("TruongMoRongChiTiet8");

                    b.Property<string>("TruongMoRongChiTiet9");

                    b.Property<decimal?>("TyLeChietKhau");

                    b.Property<string>("XuatBanPhi");

                    b.HasKey("HoaDonDienTuChiTietId");

                    b.HasIndex("DonViTinhId");

                    b.HasIndex("HangHoaDichVuId");

                    b.HasIndex("HoaDonDienTuId");

                    b.ToTable("HoaDonDienTuChiTiets");
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.LuuTruTrangThaiBBDT", b =>
                {
                    b.Property<string>("LuuTruTrangThaiBBDTId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BienBanDieuChinhId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<byte[]>("PdfDaKy");

                    b.Property<int?>("STT");

                    b.Property<bool>("Status");

                    b.Property<byte[]>("XMLDaKy");

                    b.HasKey("LuuTruTrangThaiBBDTId");

                    b.HasIndex("BienBanDieuChinhId");

                    b.ToTable("LuuTruTrangThaiBBDTs");
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.LuuTruTrangThaiBBXB", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BienBanXoaBoId");

                    b.Property<byte[]>("PdfDaKy");

                    b.Property<byte[]>("XMLDaKy");

                    b.HasKey("Id");

                    b.HasIndex("BienBanXoaBoId");

                    b.ToTable("LuuTruTrangThaiBBXBs");
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.LuuTruTrangThaiFileHDDT", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HoaDonDienTuId");

                    b.Property<byte[]>("PdfDaKy");

                    b.Property<byte[]>("XMLDaKy");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonDienTuId");

                    b.ToTable("LuuTruTrangThaiFileHDDTs");
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.NhatKyThaoTacHoaDon", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("DiaChiIp");

                    b.Property<string>("ErrorMessage");

                    b.Property<bool>("HasError");

                    b.Property<string>("HoaDonDienTuId");

                    b.Property<string>("KhachHangId");

                    b.Property<int>("LoaiThaoTac");

                    b.Property<string>("MoTa");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<DateTime>("NgayGio");

                    b.Property<string>("NguoiThucHienId");

                    b.Property<int?>("STT");

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonDienTuId");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("NguoiThucHienId");

                    b.ToTable("NhatKyThaoTacHoaDons");
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.ThongBaoChiTietHoaDonRaSoat", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36);

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<bool?>("DaGuiThongBao");

                    b.Property<string>("KyHieuHoaDon")
                        .HasMaxLength(10);

                    b.Property<byte>("LoaiApDungHD");

                    b.Property<string>("LyDoRaSoat")
                        .HasMaxLength(300);

                    b.Property<string>("MauHoaDon")
                        .HasMaxLength(15);

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(36);

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<DateTime?>("NgayLapHoaDon");

                    b.Property<string>("SoHoaDon")
                        .HasMaxLength(10);

                    b.Property<string>("ThongBaoHoaDonRaSoatId")
                        .HasMaxLength(36);

                    b.HasKey("Id");

                    b.ToTable("ThongBaoChiTietHoaDonRaSoats");
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.ThongBaoHoaDonRaSoat", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("ChucDanh")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36);

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("FileDinhKem")
                        .HasMaxLength(500);

                    b.Property<string>("HinhThuc")
                        .HasMaxLength(50);

                    b.Property<byte>("Lan");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(15);

                    b.Property<string>("MaThongDiep")
                        .HasMaxLength(50);

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(36);

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<DateTime>("NgayThongBao");

                    b.Property<string>("SoThongBaoCuaCQT")
                        .HasMaxLength(40);

                    b.Property<string>("TenCQTCapTren")
                        .HasMaxLength(120);

                    b.Property<string>("TenCQTRaThongBao")
                        .HasMaxLength(120);

                    b.Property<string>("TenNguoiNopThue")
                        .HasMaxLength(400);

                    b.Property<byte>("ThoiHan");

                    b.HasKey("Id");

                    b.ToTable("ThongBaoHoaDonRaSoats");
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.ThongDiepChiTietGuiCQT", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36);

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("HoaDonDienTuId")
                        .HasMaxLength(36);

                    b.Property<string>("KyHieuHoaDon")
                        .HasMaxLength(10);

                    b.Property<byte>("LoaiApDungHoaDon");

                    b.Property<string>("LyDo")
                        .HasMaxLength(300);

                    b.Property<string>("MaCQTCap")
                        .HasMaxLength(40);

                    b.Property<string>("MauHoaDon")
                        .HasMaxLength(15);

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(36);

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<DateTime?>("NgayLapHoaDon");

                    b.Property<byte>("PhanLoaiHDSaiSot");

                    b.Property<int?>("STT");

                    b.Property<string>("SoHoaDon")
                        .HasMaxLength(10);

                    b.Property<string>("ThongBaoChiTietHDRaSoatId")
                        .HasMaxLength(36);

                    b.Property<string>("ThongDiepGuiCQTId")
                        .HasMaxLength(36);

                    b.HasKey("Id");

                    b.ToTable("ThongDiepChiTietGuiCQTs");
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.ThongDiepGuiCQT", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36);

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<bool?>("DaKyGuiCQT");

                    b.Property<string>("DaiDienNguoiNopThue")
                        .HasMaxLength(50);

                    b.Property<string>("DiaDanh")
                        .HasMaxLength(50);

                    b.Property<string>("FileDinhKem")
                        .HasMaxLength(500);

                    b.Property<string>("FileXMLDaKy")
                        .HasMaxLength(200);

                    b.Property<string>("MaCoQuanThue")
                        .HasMaxLength(5);

                    b.Property<string>("MaDiaDanh")
                        .HasMaxLength(3);

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(15);

                    b.Property<string>("MaThongDiep")
                        .HasMaxLength(50);

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(36);

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<DateTime>("NgayGui");

                    b.Property<DateTime>("NgayLap");

                    b.Property<string>("NguoiNopThue")
                        .HasMaxLength(400);

                    b.Property<string>("TenCoQuanThue")
                        .HasMaxLength(100);

                    b.Property<string>("ThongBaoHoaDonRaSoatId")
                        .HasMaxLength(36);

                    b.HasKey("Id");

                    b.ToTable("ThongDiepGuiCQTs");
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.ThongTinChuyenDoi", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HoaDonDienTuId");

                    b.Property<DateTime>("NgayChuyenDoi");

                    b.Property<string>("NguoiChuyenDoiId");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonDienTuId");

                    b.HasIndex("NguoiChuyenDoiId");

                    b.ToTable("ThongTinChuyenDois");
                });

            modelBuilder.Entity("DLL.Entity.QuyDinhKyThuat.BangTongHopDuLieuHoaDon", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BoSungLanThu");

                    b.Property<bool>("HDDIn");

                    b.Property<string>("KyDuLieu")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("LHHoa");

                    b.Property<bool>("LanDau");

                    b.Property<string>("LoaiKyDuLieu")
                        .IsRequired()
                        .HasMaxLength(1);

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasMaxLength(14);

                    b.Property<string>("MauSo")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("NNT");

                    b.Property<int?>("NamDuLieu");

                    b.Property<DateTime?>("NgayDuLieu");

                    b.Property<DateTime>("NgayLap");

                    b.Property<string>("PhienBan")
                        .IsRequired()
                        .HasMaxLength(6);

                    b.Property<int?>("QuyDuLieu");

                    b.Property<int>("SoBTHDLieu");

                    b.Property<int?>("SuaDoiLanThu");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("TenNNT")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<int?>("ThangDuLieu");

                    b.Property<DateTime>("ThoiGianGui");

                    b.HasKey("Id");

                    b.ToTable("BangTongHopDuLieuHoaDons");
                });

            modelBuilder.Entity("DLL.Entity.QuyDinhKyThuat.BangTongHopDuLieuHoaDonChiTiet", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BangTongHopDuLieuHoaDonId");

                    b.Property<string>("DiaChi");

                    b.Property<string>("DonViTinh");

                    b.Property<string>("HoTenNguoiMuaHang");

                    b.Property<string>("KyHieu");

                    b.Property<string>("KyHieuHoaDonLienQuan");

                    b.Property<string>("MaHang");

                    b.Property<string>("MaKhachHang");

                    b.Property<string>("MaSoThue");

                    b.Property<string>("MauSo");

                    b.Property<string>("MauSoHoaDonLienQuan");

                    b.Property<DateTime?>("NgayHoaDon");

                    b.Property<string>("SoHoaDon");

                    b.Property<string>("SoHoaDonLienQuan");

                    b.Property<decimal?>("SoLuong");

                    b.Property<string>("TenHang");

                    b.Property<string>("TenKhachHang");

                    b.Property<string>("TenTrangThaiHoaDon");

                    b.Property<decimal?>("ThanhTien");

                    b.Property<string>("ThueGTGT");

                    b.Property<decimal?>("TienThueGTGT");

                    b.Property<decimal?>("TongTienThanhToan");

                    b.Property<int?>("TrangThaiHoaDon");

                    b.HasKey("Id");

                    b.ToTable("BangTongHopDuLieuHoaDonChiTiets");
                });

            modelBuilder.Entity("DLL.Entity.QuyDinhKyThuat.ChungThuSoSuDung", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DNgay")
                        .IsRequired();

                    b.Property<int>("HThuc");

                    b.Property<int?>("STT");

                    b.Property<string>("Seri")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("TNgay")
                        .IsRequired();

                    b.Property<string>("TTChuc")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.HasKey("Id");

                    b.ToTable("ChungThuSoSuDungs");
                });

            modelBuilder.Entity("DLL.Entity.QuyDinhKyThuat.DangKyUyNhiem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DNgay");

                    b.Property<string>("IdToKhai");

                    b.Property<string>("KHHDon")
                        .HasMaxLength(6);

                    b.Property<int?>("KHMSHDon");

                    b.Property<string>("MDich")
                        .HasMaxLength(255);

                    b.Property<string>("MST")
                        .HasMaxLength(14);

                    b.Property<int>("PThuc");

                    b.Property<int?>("STT");

                    b.Property<string>("THTTTKhac")
                        .HasMaxLength(50);

                    b.Property<string>("TLHDon")
                        .HasMaxLength(100);

                    b.Property<string>("TNgay");

                    b.Property<string>("TTChuc")
                        .HasMaxLength(400);

                    b.HasKey("Id");

                    b.ToTable("DangKyUyNhiems");
                });

            modelBuilder.Entity("DLL.Entity.QuyDinhKyThuat.DuLieuGuiHDDT", b =>
                {
                    b.Property<string>("DuLieuGuiHDDTId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("HoaDonDienTuId");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<int?>("STT");

                    b.Property<bool>("Status");

                    b.HasKey("DuLieuGuiHDDTId");

                    b.ToTable("DuLieuGuiHDDTs");
                });

            modelBuilder.Entity("DLL.Entity.QuyDinhKyThuat.DuLieuGuiHDDTChiTiet", b =>
                {
                    b.Property<string>("DuLieuGuiHDDTChiTietId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("DuLieuGuiHDDTId");

                    b.Property<string>("HoaDonDienTuId");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<int?>("STT");

                    b.Property<bool>("Status");

                    b.HasKey("DuLieuGuiHDDTChiTietId");

                    b.HasIndex("DuLieuGuiHDDTId");

                    b.HasIndex("HoaDonDienTuId");

                    b.ToTable("DuLieuGuiHDDTChiTiets");
                });

            modelBuilder.Entity("DLL.Entity.QuyDinhKyThuat.DuLieuKyToKhai", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FileXMLDaKy");

                    b.Property<string>("IdToKhai");

                    b.Property<string>("MST");

                    b.Property<DateTime?>("NgayKy");

                    b.Property<byte[]>("NoiDungKy");

                    b.Property<string>("Seri");

                    b.HasKey("Id");

                    b.ToTable("DuLieuKyToKhais");
                });

            modelBuilder.Entity("DLL.Entity.QuyDinhKyThuat.ThongDiepChung", b =>
                {
                    b.Property<string>("ThongDiepChungId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("FileXML");

                    b.Property<int?>("HinhThuc");

                    b.Property<string>("IdThamChieu");

                    b.Property<string>("IdThongDiepGoc");

                    b.Property<int>("LanGui");

                    b.Property<int>("LanThu");

                    b.Property<int>("MaLoaiThongDiep");

                    b.Property<string>("MaNoiGui");

                    b.Property<string>("MaNoiNhan");

                    b.Property<string>("MaSoThue");

                    b.Property<string>("MaThongDiep");

                    b.Property<string>("MaThongDiepPhanHoi");

                    b.Property<string>("MaThongDiepThamChieu");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<DateTime?>("NgayGui");

                    b.Property<DateTime?>("NgayThongBao");

                    b.Property<string>("NoiNhan");

                    b.Property<string>("PhienBan");

                    b.Property<int?>("STT");

                    b.Property<int>("SoLuong");

                    b.Property<bool>("Status");

                    b.Property<bool>("ThongDiepGuiDi");

                    b.Property<int>("TrangThaiGui");

                    b.HasKey("ThongDiepChungId");

                    b.ToTable("ThongDiepChungs");
                });

            modelBuilder.Entity("DLL.Entity.QuyDinhKyThuat.ToKhaiDangKyThongTin", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("ContentXMLChuaKy");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("FileXMLChuaKy");

                    b.Property<bool>("IsThemMoi");

                    b.Property<int?>("LoaiUyNhiem");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<DateTime>("NgayTao");

                    b.Property<bool>("NhanUyNhiem");

                    b.Property<string>("PPTinh");

                    b.Property<int?>("STT");

                    b.Property<bool>("SignedStatus");

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.ToTable("ToKhaiDangKyThongTins");
                });

            modelBuilder.Entity("DLL.Entity.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("RoleName")
                        .HasMaxLength(200);

                    b.Property<bool>("Status");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DLL.Entity.ThaoTac", b =>
                {
                    b.Property<string>("ThaoTacId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ma");

                    b.Property<int>("STT");

                    b.Property<string>("Ten");

                    b.HasKey("ThaoTacId");

                    b.ToTable("ThaoTacs");
                });

            modelBuilder.Entity("DLL.Entity.TienIch.NhatKyGuiEmail", b =>
                {
                    b.Property<string>("NhatKyGuiEmailId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("EmailGui");

                    b.Property<string>("EmailNguoiNhan");

                    b.Property<string>("KyHieu");

                    b.Property<int>("LoaiEmail");

                    b.Property<string>("MauSo");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<DateTime?>("Ngay");

                    b.Property<string>("RefId");

                    b.Property<int>("RefType");

                    b.Property<int?>("STT");

                    b.Property<string>("So");

                    b.Property<bool>("Status");

                    b.Property<string>("TenNguoiGui");

                    b.Property<string>("TenNguoiNhan");

                    b.Property<string>("TieuDeEmail");

                    b.Property<int>("TrangThaiGuiEmail");

                    b.HasKey("NhatKyGuiEmailId");

                    b.ToTable("NhatKyGuiEmails");
                });

            modelBuilder.Entity("DLL.Entity.TienIch.NhatKyTruyCap", b =>
                {
                    b.Property<string>("NhatKyTruyCapId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("DiaChiIP");

                    b.Property<string>("DoiTuongThaoTac");

                    b.Property<string>("HanhDong");

                    b.Property<string>("MoTaChiTiet");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("RefFile");

                    b.Property<string>("RefId");

                    b.Property<int>("RefType");

                    b.Property<int?>("STT");

                    b.Property<bool>("Status");

                    b.Property<string>("TenMayTinh");

                    b.Property<string>("ThamChieu");

                    b.HasKey("NhatKyTruyCapId");

                    b.ToTable("NhatKyTruyCaps");
                });

            modelBuilder.Entity("DLL.Entity.TransferLog", b =>
                {
                    b.Property<string>("TransferLogId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<DateTime>("DateTime");

                    b.Property<int>("MLTDiep");

                    b.Property<string>("MNGui");

                    b.Property<string>("MNNhan");

                    b.Property<string>("MTDTChieu");

                    b.Property<string>("MTDiep");

                    b.Property<int>("Type");

                    b.Property<string>("XMLData");

                    b.HasKey("TransferLogId");

                    b.ToTable("TransferLogs");
                });

            modelBuilder.Entity("DLL.Entity.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Address");

                    b.Property<string>("Avatar");

                    b.Property<string>("ConfirmPassword")
                        .HasMaxLength(200);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<DateTime?>("DateOfBirth");

                    b.Property<string>("Email")
                        .HasMaxLength(200);

                    b.Property<string>("FullName")
                        .HasMaxLength(200);

                    b.Property<int?>("Gender");

                    b.Property<bool?>("IsAdmin");

                    b.Property<bool?>("IsNodeAdmin");

                    b.Property<bool?>("IsOnline");

                    b.Property<int?>("LoginCount");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("Password")
                        .HasMaxLength(200);

                    b.Property<string>("Phone")
                        .HasMaxLength(200);

                    b.Property<string>("RoleId");

                    b.Property<bool>("Status");

                    b.Property<string>("Title")
                        .HasMaxLength(200);

                    b.Property<string>("UserName")
                        .HasMaxLength(200);

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DLL.Entity.User_Role", b =>
                {
                    b.Property<string>("URID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("RoleId");

                    b.Property<string>("UserId");

                    b.HasKey("URID");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("User_Roles");
                });

            modelBuilder.Entity("DLL.Entity.ViewThaoTac", b =>
                {
                    b.Property<string>("ThaoTacId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("Active");

                    b.Property<string>("FTID");

                    b.Property<string>("FunctionId");

                    b.Property<string>("Ma");

                    b.Property<string>("PemissionId");

                    b.Property<string>("RoleId");

                    b.Property<int>("STT");

                    b.Property<string>("Ten");

                    b.Property<string>("UTID");

                    b.Property<string>("UserId");

                    b.HasKey("ThaoTacId");

                    b.ToTable("ViewThaoTacs");
                });

            modelBuilder.Entity("DLL.Entity.BaoCao.BaoCaoTinhHinhSuDungHoaDonChiTiet", b =>
                {
                    b.HasOne("DLL.Entity.BaoCao.BaoCaoTinhHinhSuDungHoaDon", "BaoCaoTinhHinhSuDungHoaDon")
                        .WithMany("ChiTiets")
                        .HasForeignKey("BaoCaoTinhHinhSuDungHoaDonId");
                });

            modelBuilder.Entity("DLL.Entity.BaoCao.TruongDuLieu", b =>
                {
                    b.HasOne("DLL.Entity.BaoCao.NghiepVu", "NghiepVu")
                        .WithMany()
                        .HasForeignKey("NghiepVuId");
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.HangHoaDichVu", b =>
                {
                    b.HasOne("DLL.Entity.DanhMuc.DonViTinh", "DonViTinh")
                        .WithMany("HangHoaDichVus")
                        .HasForeignKey("DonViTinhId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.MauHoaDonThietLapMacDinh", b =>
                {
                    b.HasOne("DLL.Entity.DanhMuc.MauHoaDon", "MauHoaDon")
                        .WithMany("MauHoaDonThietLapMacDinhs")
                        .HasForeignKey("MauHoaDonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.MauHoaDonTuyChinhChiTiet", b =>
                {
                    b.HasOne("DLL.Entity.DanhMuc.MauHoaDon", "MauHoaDon")
                        .WithMany("MauHoaDonTuyChinhChiTiets")
                        .HasForeignKey("MauHoaDonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.QuyetDinhApDungHoaDonDieu1", b =>
                {
                    b.HasOne("DLL.Entity.DanhMuc.QuyetDinhApDungHoaDon", "QuyetDinhApDungHoaDon")
                        .WithMany("QuyetDinhApDungHoaDonDieu1s")
                        .HasForeignKey("QuyetDinhApDungHoaDonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.QuyetDinhApDungHoaDonDieu2", b =>
                {
                    b.HasOne("DLL.Entity.DanhMuc.QuyetDinhApDungHoaDon", "QuyetDinhApDungHoaDon")
                        .WithMany("QuyetDinhApDungHoaDonDieu2s")
                        .HasForeignKey("QuyetDinhApDungHoaDonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.ThongBaoDieuChinhThongTinHoaDonChiTiet", b =>
                {
                    b.HasOne("DLL.Entity.DanhMuc.MauHoaDon", "MauHoaDon")
                        .WithMany("ThongBaoDieuChinhThongTinHoaDonChiTiets")
                        .HasForeignKey("MauHoaDonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DLL.Entity.DanhMuc.ThongBaoDieuChinhThongTinHoaDon", "ThongBaoDieuChinhThongTinHoaDon")
                        .WithMany("ThongBaoDieuChinhThongTinHoaDonChiTiets")
                        .HasForeignKey("ThongBaoDieuChinhThongTinHoaDonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.ThongBaoKetQuaHuyHoaDonChiTiet", b =>
                {
                    b.HasOne("DLL.Entity.DanhMuc.MauHoaDon", "MauHoaDon")
                        .WithMany("ThongBaoKetQuaHuyHoaDonChiTiets")
                        .HasForeignKey("MauHoaDonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DLL.Entity.DanhMuc.ThongBaoKetQuaHuyHoaDon", "ThongBaoKetQuaHuyHoaDon")
                        .WithMany("ThongBaoKetQuaHuyHoaDonChiTiets")
                        .HasForeignKey("ThongBaoKetQuaHuyHoaDonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DLL.Entity.DanhMuc.ThongBaoPhatHanhChiTiet", b =>
                {
                    b.HasOne("DLL.Entity.DanhMuc.MauHoaDon", "MauHoaDon")
                        .WithMany("ThongBaoPhatHanhChiTiets")
                        .HasForeignKey("MauHoaDonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DLL.Entity.DanhMuc.ThongBaoPhatHanh", "ThongBaoPhatHanh")
                        .WithMany("ThongBaoPhatHanhChiTiets")
                        .HasForeignKey("ThongBaoPhatHanhId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DLL.Entity.Function_Role", b =>
                {
                    b.HasOne("DLL.Entity.Function", "Function")
                        .WithMany("Function_Roles")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DLL.Entity.Permission", "Permission")
                        .WithMany("Function_Roles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DLL.Entity.Role", "Role")
                        .WithMany("Function_Roles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DLL.Entity.Function_ThaoTac", b =>
                {
                    b.HasOne("DLL.Entity.Function", "Function")
                        .WithMany()
                        .HasForeignKey("FunctionId");

                    b.HasOne("DLL.Entity.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId");

                    b.HasOne("DLL.Entity.ThaoTac", "ThaoTac")
                        .WithMany()
                        .HasForeignKey("ThaoTacId");

                    b.HasOne("DLL.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("DLL.Entity.Function_User", b =>
                {
                    b.HasOne("DLL.Entity.Function", "Function")
                        .WithMany("Function_Users")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DLL.Entity.Permission", "Permission")
                        .WithMany("Function_Users")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DLL.Entity.User", "User")
                        .WithMany("Function_Users")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DLL.Entity.PhanQuyenMauHoaDon", b =>
                {
                    b.HasOne("DLL.Entity.DanhMuc.MauHoaDon", "MauHoaDon")
                        .WithMany()
                        .HasForeignKey("MauHoaDonId");

                    b.HasOne("DLL.Entity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("DLL.Entity.QuanLy.BoKyHieuHoaDon", b =>
                {
                    b.HasOne("DLL.Entity.DanhMuc.MauHoaDon", "MauHoaDon")
                        .WithMany("BoKyHieuHoaDons")
                        .HasForeignKey("MauHoaDonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DLL.Entity.QuyDinhKyThuat.ThongDiepChung", "ThongDiepChung")
                        .WithMany("BoKyHieuHoaDons")
                        .HasForeignKey("ThongDiepChungId");
                });

            modelBuilder.Entity("DLL.Entity.QuanLy.NhatKyXacThucBoKyHieu", b =>
                {
                    b.HasOne("DLL.Entity.QuanLy.BoKyHieuHoaDon", "BoKyHieuHoaDon")
                        .WithMany("NhatKyXacThucBoKyHieus")
                        .HasForeignKey("BoKyHieuHoaDonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.BienBanDieuChinh", b =>
                {
                    b.HasOne("DLL.Entity.QuanLyHoaDon.HoaDonDienTu", "HoaDonBiDieuChinh")
                        .WithMany()
                        .HasForeignKey("HoaDonBiDieuChinhId");

                    b.HasOne("DLL.Entity.QuanLyHoaDon.HoaDonDienTu", "HoaDonDieuChinh")
                        .WithMany()
                        .HasForeignKey("HoaDonDieuChinhId");
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.BienBanXoaBo", b =>
                {
                    b.HasOne("DLL.Entity.QuanLyHoaDon.HoaDonDienTu", "HoaDonDienTu")
                        .WithMany()
                        .HasForeignKey("HoaDonDienTuId");

                    b.HasOne("DLL.Entity.DanhMuc.DoiTuong", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId");
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.HoaDonDienTu", b =>
                {
                    b.HasOne("DLL.Entity.QuanLy.BoKyHieuHoaDon", "BoKyHieuHoaDon")
                        .WithMany("HoaDonDienTus")
                        .HasForeignKey("BoKyHieuHoaDonId");

                    b.HasOne("DLL.Entity.DanhMuc.DoiTuong", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId");

                    b.HasOne("DLL.Entity.DanhMuc.LoaiTien", "LoaiTien")
                        .WithMany()
                        .HasForeignKey("LoaiTienId");

                    b.HasOne("DLL.Entity.DanhMuc.MauHoaDon", "MauHoaDon")
                        .WithMany()
                        .HasForeignKey("MauHoaDonId");

                    b.HasOne("DLL.Entity.DanhMuc.DoiTuong", "NguoiLap")
                        .WithMany()
                        .HasForeignKey("NguoiLapId");

                    b.HasOne("DLL.Entity.DanhMuc.DoiTuong", "NhanVienBanHang")
                        .WithMany()
                        .HasForeignKey("NhanVienBanHangId");
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.HoaDonDienTuChiTiet", b =>
                {
                    b.HasOne("DLL.Entity.DanhMuc.DonViTinh", "DonViTinh")
                        .WithMany()
                        .HasForeignKey("DonViTinhId");

                    b.HasOne("DLL.Entity.DanhMuc.HangHoaDichVu", "HangHoaDichVu")
                        .WithMany()
                        .HasForeignKey("HangHoaDichVuId");

                    b.HasOne("DLL.Entity.QuanLyHoaDon.HoaDonDienTu", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("HoaDonDienTuId");
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.LuuTruTrangThaiBBDT", b =>
                {
                    b.HasOne("DLL.Entity.QuanLyHoaDon.BienBanDieuChinh", "BienBanDieuChinh")
                        .WithMany()
                        .HasForeignKey("BienBanDieuChinhId");
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.LuuTruTrangThaiBBXB", b =>
                {
                    b.HasOne("DLL.Entity.QuanLyHoaDon.BienBanXoaBo", "BienBanXoaBo")
                        .WithMany()
                        .HasForeignKey("BienBanXoaBoId");
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.LuuTruTrangThaiFileHDDT", b =>
                {
                    b.HasOne("DLL.Entity.QuanLyHoaDon.HoaDonDienTu", "HoaDonDienTu")
                        .WithMany()
                        .HasForeignKey("HoaDonDienTuId");
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.NhatKyThaoTacHoaDon", b =>
                {
                    b.HasOne("DLL.Entity.QuanLyHoaDon.HoaDonDienTu", "HoaDonDienTu")
                        .WithMany()
                        .HasForeignKey("HoaDonDienTuId");

                    b.HasOne("DLL.Entity.DanhMuc.DoiTuong", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId");

                    b.HasOne("DLL.Entity.User", "NguoiThucHien")
                        .WithMany()
                        .HasForeignKey("NguoiThucHienId");
                });

            modelBuilder.Entity("DLL.Entity.QuanLyHoaDon.ThongTinChuyenDoi", b =>
                {
                    b.HasOne("DLL.Entity.QuanLyHoaDon.HoaDonDienTu", "HoaDonDienTu")
                        .WithMany()
                        .HasForeignKey("HoaDonDienTuId");

                    b.HasOne("DLL.Entity.DanhMuc.DoiTuong", "NguoiChuyenDoi")
                        .WithMany()
                        .HasForeignKey("NguoiChuyenDoiId");
                });

            modelBuilder.Entity("DLL.Entity.QuyDinhKyThuat.DuLieuGuiHDDTChiTiet", b =>
                {
                    b.HasOne("DLL.Entity.QuyDinhKyThuat.DuLieuGuiHDDT", "DuLieuGuiHDDT")
                        .WithMany("DuLieuGuiHDDTChiTiets")
                        .HasForeignKey("DuLieuGuiHDDTId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DLL.Entity.QuanLyHoaDon.HoaDonDienTu", "HoaDonDienTu")
                        .WithMany()
                        .HasForeignKey("HoaDonDienTuId");
                });

            modelBuilder.Entity("DLL.Entity.User", b =>
                {
                    b.HasOne("DLL.Entity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DLL.Entity.User_Role", b =>
                {
                    b.HasOne("DLL.Entity.Role", "Role")
                        .WithMany("User_Roles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DLL.Entity.User", "User")
                        .WithMany("User_Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
