namespace DLL.Enums
{
    public enum LoaiChiTietTuyChonNoiDung
    {
        CustomHangHoaDichVu = -4,
        CustomNguoiMua = -3,
        CustomThongTinHoaDon = -2,
        CustomNguoiBan = -1,
        ///////////////////////////////
        None,
        TenDonViNguoiBan,
        MaSoThueNguoiBan,
        DiaChiNguoiBan,
        DienThoaiNguoiBan,
        FaxNguoiBan,
        WebsiteNguoiBan,
        EmailNguoiBan,
        SoTaiKhoanNguoiBan,
        /////////////////////////
        TenLoaiHoaDon,
        TenKhacLoaiHoaDon,
        TenMauHoaDon,
        NgayThangNamTieuDe,
        ////////////////////////
        MauSo,
        KyHieu,
        SoHoaDon,
        ////////////////////////,
        HoTenNguoiMua,
        TenDonViNguoiMua,
        MaSoThueNguoiMua,
        DiaChiNguoiMua,
        HinhThucThanhToan,
        SoTaiKhoanNguoiMua,
        ThoiHanThanhToan,
        DiaChiGiaoHang,
        ////////////////////////,
        STT,
        MaHang,
        TenHangHoaDichVu,
        QuyCach,
        DonViTinh,
        SoLuong,
        DonGia,
        ThanhTien,
        GhiChuHHDV,
        ////////////////////////
        TyLeChietKhau,
        SoTienChietKhau,
        CongTienHang,
        ThueSuatGTGT,
        TienThueGTGT,
        TongTienThanhToan,
        SoTienBangChu,
        GhiChuTongTien,
        ///////////////////////
        TyGia,
        QuyDoi,
        ///////////////////////
        TieuDeKyNguoiChuyenDoi,
        KyGhiRoHoTenNguoiChuyenDoi,
        TieuDeKyNguoiMua,
        KyGhiRoHoTenNguoiMua,
        TieuDeKyNguoiBan,
        KyGhiRoHoTenNguoiBan,
        ///////////////////////
        TraCuuTai,
        CanKiemTraDoiChieu,
        PhatHanhBoi,
        LinkTraCuu,
        MaTraCuu
    }
}
