//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKSOFT.TVAN.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDon
    {
        public System.Guid ID { get; set; }
        public System.Guid TIVanID { get; set; }
        public string THDon { get; set; }
        public string KHMSHDon { get; set; }
        public string KHHDon { get; set; }
        public long SHDon { get; set; }
        public System.DateTime NLap { get; set; }
        public string DVTTe { get; set; }
        public decimal TGia { get; set; }
        public string HTTToan { get; set; }
        public string NBTen { get; set; }
        public string NBMST { get; set; }
        public string NBDChi { get; set; }
        public string NMTen { get; set; }
        public string NMMST { get; set; }
        public string NMDChi { get; set; }
        public decimal TgTCThue { get; set; }
        public decimal TgTThue { get; set; }
        public decimal TTCKTMai { get; set; }
        public decimal TgTTTBSo { get; set; }
        public string TgTTTBChu { get; set; }
    }
}
