//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GatewayServiceTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123456a@A")]
        public string USER_PASS {
            get {
                return ((string)(this["USER_PASS"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gateway.vnpt-ca.vn/signservice/v4/api_gateway")]
        public string SERVICE_URL {
            get {
                return ((string)(this["SERVICE_URL"]));
            }
            set {
                this["SERVICE_URL"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tuanbs@vnpt.vn")]
        public string ENTERPRISE_ACC {
            get {
                return ((string)(this["ENTERPRISE_ACC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hauhm1005@gmail.com")]
        public string USER_ACC {
            get {
                return ((string)(this["USER_ACC"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4d00-637756770090774213.apps.smartcaapi.com")]
        public string APP_ID {
            get {
                return ((string)(this["APP_ID"]));
            }
            set {
                this["APP_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mzg2NTA2NTI-OTVkZC00ZDAw")]
        public string APP_SECRET {
            get {
                return ((string)(this["APP_SECRET"]));
            }
            set {
                this["APP_SECRET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://rmgateway.vnptit.vn/auth/token")]
        public string SERVICE_GET_TOKENURL {
            get {
                return ((string)(this["SERVICE_GET_TOKENURL"]));
            }
            set {
                this["SERVICE_GET_TOKENURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://rmgateway.vnptit.vn/csc/credentials/list")]
        public string URL_CREDENTIALS_LIST {
            get {
                return ((string)(this["URL_CREDENTIALS_LIST"]));
            }
            set {
                this["URL_CREDENTIALS_LIST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://rmgateway.vnptit.vn/csc/credentials/info")]
        public string URL_CREDENTIALS_INFO {
            get {
                return ((string)(this["URL_CREDENTIALS_INFO"]));
            }
            set {
                this["URL_CREDENTIALS_INFO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://rmgateway.vnptit.vn/csc/signature/signhash")]
        public string URL_SIGN_HASH {
            get {
                return ((string)(this["URL_SIGN_HASH"]));
            }
            set {
                this["URL_SIGN_HASH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://rmgateway.vnptit.vn/csc/credentials/gettraninfo")]
        public string URL_GET_TRAN_ID {
            get {
                return ((string)(this["URL_GET_TRAN_ID"]));
            }
            set {
                this["URL_GET_TRAN_ID"] = value;
            }
        }
    }
}
